### ISSUE TITLE
comandline options are kind of redundant

### ISSUE THREAD

**Issue by arturoc** [openframeworks/projectGenerator#10]
this is kind of weird:

```bash
projectGenerator -o . -c -p apps/myprojects/example
```

the project to create or update always needs to be specified so always adding -p seems redundant.

this:

```bash
projectGenerator -o . -c apps/myprojects/example
```

would be better.

Also having to always specify -c or -u seems redundant too. By default it should create if the project doesn't exists yet or update if it's already there like:

```bash
projectGenerator -o . apps/myprojects/example
```

that way if we have an env var to specify where OF is located (which should be explained in the usage maessage) we can do:

```bash
projectGenerator apps/myprojects/example
```

to create a project with the default settings otherwise the usage is too complicated.

also in the message, usage, usually specifies the format in which it has to be called, ie:

```
usage: commandline [options] path
```

or if the command is mandatory:

```
usage commandline [options] command path
```

**Comment by ofZach** [comment]
Makes sense and will definitely simplify things :). Looking at those changes now.

**Comment by ofZach** [comment]
PS: I love any change that involves deleting code :)   remembering the mantra that good programmers write negative lines of code....

**Comment by ofZach** [comment]
the only question is do we treat the path parameter as a name (ie, join the current path with name) or as a full path?  My intuition is to check and see if it's an absolute path (then don't join) if not, join with the current path so we can use the command line locally to where we are running it.   that would allow you to easily use drag and drop for folders on osx, etc...

**Comment by arturoc** [comment]
i think that check is already workinh now. i's done by ofDirectory when you create or open it

**Comment by ofZach** [comment]
can you try the PR now -  this commit addresses this issue: 

https://github.com/openframeworks/projectGenerator/commit/36a568bc5c4de48e5bbad338b746224374f0f3c4

this is the current help screen if it's helpful: 

usage:


	      projectGenerator [options] pathName

	if pathName exists, project is updated
	if pathName doesn't exist, project is created

	OPTIONS:

	lists should be comma seperated and in quotes if there are spaces
	you can use : or = for parameter based options, such as -o=/usr/...

	-r, --recursive                                 update recursively (applies
	                                                only to update)
	-h, --help
	-x"platform list", --platforms="platform list"  platform list
	-a"addons list", --addons="addons list"         addons list
	-o"OF path", --ofPath="OF path"                 openframeworks path
	-v, --verbose                                   run verbose
	-d, --dryrun                                    don't change files

prob could examples and a short note about the env variable.

**Comment by ofZach** [comment]
regarding the check: 

https://github.com/openframeworks/projectGenerator/blob/commandLineWork/commandLine/src/main.cpp#L454-L463

I think we need to do this here since we check if the directory exists to pick the mode....

**Comment by ofZach** [comment]
closing this issue since I think it's been resolved
