### ISSUE TITLE
Fix Travis for projectGenerator to do a test build

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#101]
- I'm not really sure what travis is currently doing... might want to fix it so it works for PR's.

- Whatever it is doing on the master branch it can still do that and just on master if it needs to. 
- However the OpenSSL part is breaking PR's.

```
0.00s$ openssl aes-256-cbc -K $encrypted_cd38768cbb9d_key -iv $encrypted_cd38768cbb9d_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_cd38768cbb9d_key -iv $encrypted_cd38768cbb9d_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by arturoc** [comment]
the travis build, apart from testing the PR builds the PG and uploads it to our servers so the nightly builds always have the latest version. i suspect that PRs (ie: when the commit doesn't come from master) make the part that generates the key for encrypting fail, i'll look into it

**Comment by danoli3** [comment]
If you put it into a matrix, you can use a whitelist:

branches:
  only:
    - master

**Comment by arturoc** [comment]
what if i want to make the compiler run but not the before_install?

**Comment by arturoc** [comment]
i think i found it

**Comment by danoli3** [comment]
Ah nice, I was going to suggest maybe: if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then

**Comment by arturoc** [comment]
:) yeah that's what i did
