### ISSUE TITLE
Remove STALE* Branches

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#102]
Since I forked recently... A lot of stale branches need some sawing off.

**Comment by danoli3** [comment]
DO NOT REMOVE STABLE BRANCHES * :stuck_out_tongue_closed_eyes:

**Comment by mattfelsen** [comment]
Looks like these can all be safely deleted. Not sure if the others are work-in-progress or abandoned work
```
$ git branch --merged
  icon
  localAddonsWork
* master
  openInIDE
  osxFix
  skipSomeAddons
  travis
  update projects
```

**Comment by arturoc** [comment]
just removed them, thanks!
