### ISSUE TITLE
pg is not utf-8 friendly on OSX

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#111]
I've heard reports that utf-8 files are getting encoded wrong when added to the project.  Also, the src code for the template is encoded as "western".

I'm pretty sure the fix is two part: 

a) this encoding choice

https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L56-L57

should be 4 (utf-8) and not 30 so incoming src files are treated as utf-8.  

b) src files for the template need to be changed as well to utf-8

it would be good to have a tests cases to study, such as an addon that has japanese comments, etc.

**Comment by arturoc** [comment]
this is also reported here: https://github.com/openframeworks/openFrameworks/issues/4728

**Comment by bakercp** [comment]
Fix submitted.
