### ISSUE TITLE
Add readme to repo root

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/projectGenerator#112]
We've got some good docs in the commandLine and frontend dirs, but nothing in the root to help direct people to them! Filing this issue mostly as a reminder to myself...I can try and write something soon – looks like I can't assign myself this ticket since I don't have permission but anyone else is free to do so :smile:

**Comment by ofTheo** [comment]
@mattfelsen @ofZach - totally feeling the need for this! 
I have been trying to build the current PG and its really not clear what the correct workflow is. 

Is there any documentation for working with the PG that we could put into a ReadMe. 
Also would be good to note how we update the PG used in the distributed releases.

**Comment by mattfelsen** [comment]
Eep, 8 months and I never got around to writing anything! 😬 

I think the most documented info around building the command line & frontend PG apps is here:
https://github.com/openframeworks/projectGenerator/blob/master/frontend/readme.md

I'm not sure if info about how the PG is packaged is written anywhere, but I think the bulk of the code is in this script:
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh

**Comment by ofZach** [comment]
yeah the thing about this repo is that it's kind of 3 or 4 things put together and wasn't organized together before so the info is not all together. 

IIRC I think the hardest part is the build script, since you are basically throwing the command line tool together with this node application.   I will take a look at everything and write some notes.

**Comment by haschdl** [comment]
Hello! Also recommending good enough readme/contributing documents to be published in order to facilitate triage and engagement. Right one has to navigate a maze of open PR’s and issues, it’s very hard to find a way to contribute.

Readme.md should be the first  thing in every project 😁
