### ISSUE TITLE
problem with iOS project creation

### ISSUE THREAD

**Issue by arturoc** [openframeworks/projectGenerator#118]
the logs for the nightly builds are reporting the following problem when generating iOS projects:

```
[ error ] ofFile: copyTo(): source file /home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/scripts/templates/ios/bin/data/Default-568h@2x~iphone.png does not exist
[ error ] ofFile: copyTo(): source file /home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/scripts/templates/ios/bin/data/Default.png does not exist
[ error ] ofFile: copyTo(): source file /home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/scripts/templates/ios/bin/data/Default@2x.png does not exist
[ error ] ofFile: copyTo(): source file /home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/scripts/templates/ios/bin/data/Icon.png does not exist
[ error ] ofFile: copyTo(): source file /home/ofadmin/openFrameworks/scripts/dev/openFrameworks_pkg_creation/scripts/templates/ios/bin/data/Icon@2x.png does not exist
```

Not sure where the error is coming from or if it's critical though. Seems strange that it's trying to copy a file from the templates that wouldn't exist so it might be some error in the path solving when copying or something similar

**Comment by ofZach** [comment]
hmm. pinging @danoli3 - I think it has to do with this: 

https://github.com/openframeworks/openFrameworks/commit/7af3e9bae700f9308ba5d8a5aa75a5a3dc133d00

and needing to maybe update this: 

https://github.com/openframeworks/projectGenerator/blame/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L344-L359

**Comment by arturoc** [comment]
yeah looks like, that last bit in the PG code should probably copy all the contents of the folder using ofDirectory instead of hardcoding the exact files

**Comment by danoli3** [comment]
Ah yes! I was meant to update this when we merged the new splash / icons! I'll PR to Project generator now. I have it already done.
