### ISSUE TITLE
overall - much better text based output

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#12]
try to remove unnecessary errors and warnings in the project generator to make it easier to read

**Comment by Daandelange** [comment]
Still one "dirty" notice remaining on updating projects :
`[notice ] PG_OF_PATH not set (see help), -o parameter needs to be set (-h for options)` while the `-o"/Developper/OpenFrameworks` param is set.
Via IM you said it's something related to ENV_VARIABLE

**Comment by ofZach** [comment]
yes I think if -o is passed in we shouldn't say anything and use that (we are) but if -o is not passed in, explain in more english language that you need -o OR PG_OF_PATH (env variable) set.  will think about phrasing on this.

**Comment by ofZach** [comment]
I think this is fixed now for the most part, closing...
