### ISSUE TITLE
stdout maxBuffer exceeded.

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#122]
to recreate in 0.9.2 -- use ofxCv, pull the examples out into a new folder, use verbose, hit update multiple: 

```
stdout maxBuffer exceeded.


(command used:"/Users/zachlieberman/Downloads/of_v0.9.2_osx_release/projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator" -r -v -o"/Users/zachlieberman/Downloads/of_v0.9.2_osx_release" -p"osx" "/Users/zachlieberman/Downloads/of_v0.9.2_osx_release/apps/cv")

```

looks like it's related to this: 

http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

running from the command from the command line is def ok.

**Comment by miccferr** [comment]
Hi!

just want to confirm that I ran in the exact same error (`stdout maxBuffer exceeded.` ) when creating an XCode project from [an existing folder](https://github.com/ml4a/ml4a-ofx/tree/master/apps/FaceClassifier) with the projectGenerator app.

The project requires the following addons `ofxCv, ofxGrt, ofxOpenCv, ofxFaceTracker2`. 

Following #121, I tried removing all the folders containing examples in the required addons folders, but to no avail.

I can confirm though that running from the command-line definitely works.

```
[notice ] project created! 
[notice ] -----------------------------------------------


1 project created [notice ] in 1.73658 seconds
```

Thank you!

**Comment by zhaozj89** [comment]
@miccferr , how to run from command-line? I came across the same problem when I tried to generate a XCode project. Thanks.

**Comment by lg3bass** [comment]
@zhaozj89  Q: how to run from command-line?

I ran into the "stdout maxBuffer exceeded" issue using the project generator in OF9.8.   If somebody else want to know, here is how to run the command line project generator. 

MY-MAC:~ Me$ pwd
/Users/Me
MY-MAC:~ Me$ ./Documents/OpenFrameworks/of_v0.9.8_osx_release/projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator  -o"/Users/Me/Documents/OpenFrameworks/of_v0.9.8_osx_release" -a"ofxAbletonLink,ofxAudioDecoder,ofxDatGui,ofxMSATimer,ofxRange,ofxTextInputField,ofxTimeMeasurements,ofxTimecode,ofxTimeline,ofxTween,ofxXmlSettings" -p"osx" "/Users/Me/Documents/OpenFrameworks/of_v0.9.8_osx_release/apps/myApps/test3"

[notice ] -----------------------------------------------
[notice ] setting OF path to: /Users/Me/Documents/OpenFrameworks/of_v0.9.8_osx_release
[notice ] from -o option
[notice ] target platform is: osx
[notice ] project path is: /Users/Me/Documents/OpenFrameworks/of_v0.9.8_osx_release/apps/myApps/test3
[notice ] setting up new project /Users/Me/Documents/OpenFrameworks/of_v0.9.8_osx_release/apps/myApps/test3
[ error ] Error parsing ofxAbletonLink addon_config.mk
		line 18: 	ADDON_NAME = ofxAbletonLive
		addon name in filesystem ofxAbletonLink doesn't match with addon_config.mk ofxAbletonLive
[notice ] adding addon ofxAbletonLink
[notice ] adding addon ofxAudioDecoder
[notice ] adding addon ofxDatGui
[notice ] adding addon ofxMSATimer
[notice ] adding addon ofxRange
[notice ] adding addon ofxTextInputField
[notice ] adding addon ofxTimeMeasurements
[notice ] adding addon ofxTimecode
[ error ] Error parsing ofxTimeline addon_config.mk
		line 67: win_cb:
		sectionName unknown not recognized
[ error ] Error parsing ofxTimeline addon_config.mk
		line 68: vs2010:
		sectionName unknown not recognized
[ error ] Error parsing ofxTimeline addon_config.mk
		line 69: iphone:
		sectionName unknown not recognized
[ error ] Error parsing ofxTimeline addon_config.mk
		line 70: android:
		sectionName unknown not recognized
[notice ] adding addon ofxTimeline
[notice ] adding addon ofxTween
[notice ] adding addon ofxXmlSettings
[notice ] saving addons.make
[notice ] project created! 
[notice ] -----------------------------------------------


1 project created [notice ] in -3.24628 second

**Comment by miccferr** [comment]
@zhaozj89 sorry for the delayed reply. 

The example posted by @lg3bass is what I've done as well. Basically run:

`/PATH-TO/openFrameworks/projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator -v -o "/PATH-TO/openFrameworks" -a "ofxCv,ofxFaceTracker2,ofxOsc,ofxOpenCv,ofxControl" -p "osx" "/PATH-TO/openFrameworks/apps/myApps/FaceTracker2OSC"`

the command is fairly long due to the paths and looks all crumbled up here Github. If you copy/paste it in your terminal I'm sure it'll make much more sense

**Comment by zhaozj89** [comment]
Thanks all. It works for my case now.

**Comment by BrianSipple** [comment]
FWIW, I ran in to this error using the latest 0.9.8 download, and I had success when I unchecked the `Verbose output` option in the settings tab.
