### ISSUE TITLE
Command line pg ofPath option

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#126]
I am not able to set the ofPath using the command line options.

This is how I am calling it:
```sh
/Users/thomasgeissl/programming/of/ofTG/apps/projectGenerator/commandLine/bin/projectGenerator.app/Contents/MacOS/projectGenerator --ofPath /Users/thomasgeissl/programming/of/ofTG --addons ofxMidi
```

And here is the error message:
```sh
[ error ] no OF path set... please use -o or --ofPath or set a PG_OF_PATH environment variable
```

Is this a bug or did I something wrong?

**Comment by mattfelsen** [comment]
Hey @thomasgeissl. I don't have a computer to test but can you try either of these syntaxes:

`--ofPath=/Users/...`
or
`--o"/Users/..."`

You can also use an environment variable to specify the path so you don't have to pass it every time you run the command line tool. There's some more info on that at the bottom of the readme here:
https://github.com/openframeworks/projectGenerator/blob/master/commandLine/readme.md

**Comment by thomasgeissl** [comment]
Thanks for your answer. It works.
Sorry, I haven't checked the readme.
