### ISSUE TITLE
command line tool error on VS when built by 32bit / 64bit

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#13]
I've updated the vs project files for the command line tool -- when I compile it I get these link errors: 

	Error	LNK2001	unresolved external symbol "public: static class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const LibraryBinary::archs" (?archs@LibraryBinary@@2V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@B)	commandLine	

	C:\Users\zach\Desktop\openFrameworks\apps\projectGenerator\commandLine\Utils.obj	1
	Error	LNK2001	unresolved external symbol "public: static class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const LibraryBinary::targets" (?targets@LibraryBinary@@2V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@B)	commandLine	C:\Users\zach\Desktop\openFrameworks\apps\projectGenerator\commandLine\Utils.obj	1

**Comment by ofZach** [comment]
sorry my bad, I see that I need to update master for the addon changes.... closing.

**Comment by LeoColomb** [comment]
I get the same error.
Do you have some details about what needs to be updated?
