### ISSUE TITLE
Pressing Import while a file import dialog is already open, opens another file dialog.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/projectGenerator#130]
You can keep opening file dialogs by pressing import.

Solution is probably to disable the PG gui while a file dialog is open.

**Comment by Daandelange** [comment]
Would be easier to implement by flagging the dialog "open/closed" and disable the button click if open, but disabling the whole gui could prevent other issues like this.
_I'll look at this in July / August if not solved; but anybody feel free to solve_ :)

**Comment by Daandelange** [comment]
This issue should be solved in the commit above.

**Comment by bakercp** [comment]
Cool!
