### ISSUE TITLE
Suggestion: Drag and drop any folder to load project name and project path

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#134]
I'm updating some examples from other people addons and it would be great just to be able to drag and drop the example folder inside project generator and load everything to generate a new XCode project file with everything up to date.
Thanks!

**Comment by Daandelange** [comment]
Hello, we've been [discussing this feature](https://github.com/openframeworks/projectGenerator/issues/40) in the past and I started implementing it but it's not ready to be merged. I might have some time to look back at this next month.

**Comment by Daandelange** [comment]
@dimitre Could you close this issue for clarity ?
It's a duplicate and a PR has been submitted. :)

**Comment by dimitre** [comment]
sure thing
