### ISSUE TITLE
Instructions for building commandLine projectGenerator

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#147]
I want to use local addons, and I found from a forum thread that I need to use the command line PG. So I tried to checkout the submodule:

```
$ cd openFrameworks
$ git submodule init
$ git submodule update
```

This lead to some weird errors:

```
fatal: Not a git repository: /Users/kyle/Documents/openFrameworks/apps/projectGenerator/../../.git/modules/apps/projectGenerator
Failed to clone 'apps/projectGenerator'. Retry scheduled
BUG: submodule considered for cloning,doesn't need cloning any more?
fatal: Not a git repository: ../../.git/modules/apps/projectGenerator
Unable to fetch in submodule path 'apps/projectGenerator'
```

So instead I tried just cloning the repo directly to where it was supposed to be:

```
$ cd apps
$ rm -rf projectGenerator
$ git clone https://github.com/openframeworks/projectGenerator.git
```

Then I opened the commandLine xcodeproj, but it won't compile because it's looking for `glm.hpp`

I tried to roll back to an older version of OF without glm, but then it was looking for ofxPoco.

Is there so in-between version that works? Or am I just doing this wrong?

Thanks :)

**Comment by mattfelsen** [comment]
Hey @kylemcdonald. I haven't used OF or the PG from master in a while, but I've been using the PG from an 0.9.x release with local addons without issue. 

Usually I'll use the PG GUI to create a project with any global addons first (like ofxOsc), then edit the generated addons.make file to add my local addons (usually something like ../../addons/ofxCv for my project structure), then switch back to the PG and see my local addons update (tab between the project name and folder path if needed), and hit update . 

Hopefully that works for you

**Comment by kylemcdonald** [comment]
Hah! That's what I was just doing :) It looks like it works.

I think the issue above is related to cloning out a fresh copy of the openFrameworks repo, and there's some trick for pulling all the libs I can't remember.

**Comment by arturoc** [comment]
we've removed the libraries from the repo recently. to download them you have to run scripts/osx/download_libs.sh

**Comment by kylemcdonald** [comment]
thanks @arturoc! i figured it out eventually :) so excited for the history to get cleaned at some point! the repo will be 100x smaller!
