### ISSUE TITLE
projectGeneratorLegacy not able to check addons correctly

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#16]
I Just pulled current master of openframeworks and projectGenerator and compiled projectGeneratorLegacy successfully. Everytime I try selecting an addon, the addon above, or two steps above gets checked, depending on the position. 
ProjectGeneratorSimple and guiFromParameters work as expected.
I am on Ubuntu 15.04.

**Comment by Daandelange** [comment]
Hmm, weird, on OS X it works as expected...
But as we're working on a brand new PG, I think it's not worth fixing this... (?)

**Comment by thomasgeissl** [comment]
I will have a look at this today to be sure it is not an ofxGui bug. It is probably something I did wrong on this machine. Gonna test it on a debian machine too. 
I agree, as the gui examples work fine and you are working on the new pg, it is probably not worth fixing this.

**Comment by thomasgeissl** [comment]
It works normally if I do not set the position for panelAddons.
https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorLegacy/src/ofApp.cpp#L470
Setting the panel position in guiFromParameters example do not produce this bug.
I do not see any difference except the panelWidth.

**Comment by thomasgeissl** [comment]
It only happens when using glut window. When I change guiFromParameters to use glut, it behaves as described above.
@arturoc Do you know more about this?
Do you want me to close this an file a bug at the main repo?
