### ISSUE TITLE
VS 2017 version still uses 2015 platform

### ISSUE THREAD

**Issue by prisonerjohn** [openframeworks/projectGenerator#175]
I just downloaded the `vs2017` nightly and noticed that the Project Generator still builds a vs2015 project.

The app itself only shows "Visual Studio 2015" as a platform option:
![pg-vs](https://user-images.githubusercontent.com/119702/38318624-c737d9c6-37fd-11e8-87fb-4ca4b2eec667.PNG)

When opening the project in VS 2017, we need to retarget the solution to use `v141` of the Platform tools:
![pg-retarget](https://user-images.githubusercontent.com/119702/38318654-db1bbf0c-37fd-11e8-9095-bc2d726dae3a.PNG)

**Comment by roymacdonald** [comment]
Hi, at least the issue of needing to retarget is quite simple to fix.
@arturo mentioned in the ofDev mailing list that we need to change it for each distribution, but I think that it is much simpler than that.

the file `openFrameworks_folder/scripts/templates/vs/emptyExample.vcxproj`
needs the following line to be changed from (it shows up 4 times, a simple find and replace will work)
`<PlatformToolset>v140</PlatformToolset>`
to
`<PlatformToolset>v141</PlatformToolset>`
save and that's all

So if we're supporting both VS2015 and VS2017 we need to make a different template for each, and in PG have two options that point to either template.
I might be oversimplifying all this but I've been doing this fix manually for a while now and it seems quite straight forwards, although I haven't looked in depth in PG to really tell how much work this would be. I'll try to take a look 
cheers

**Comment by ofTheo** [comment]
If that is the only change, could we just generate separate protect files for both?

**Comment by roymacdonald** [comment]
right, that's what I mean. The thing is that I don't know how that need to be done in PG.

**Comment by arturoc** [comment]
I thought that flag would be in the common settings but if it is in the template then we can just generate a new template for vs2017 and move add it to the PG. i don't know very much about the electron app either though. @ofZach is the one who probably knows how to go about it.
