### ISSUE TITLE
./buildPG.sh on linux not cloning correctly

### ISSUE THREAD

**Issue by drewLo** [openframeworks/projectGenerator#177]
In an attempt to set up a dev environment, after initializing projectGenerator as a submodule. 
```
λ ~/Development/oF/openFrameworks/apps/projectGenerator/scripts/linux/ b259357* ./buildPG.sh 
Cloning into 'openFrameworks'...
remote: Counting objects: 3253, done.
remote: Compressing objects: 100% (2681/2681), done.
remote: Total 3253 (delta 602), reused 2065 (delta 333), pack-reused 0
Receiving objects: 100% (3253/3253), 52.87 MiB | 6.20 MiB/s, done.
Resolving deltas: 100% (602/602), done.
Checking out files: 100% (2999/2999), done.
mv: cannot stat 'projectGenerator': No such file or directory
```
Looks like the shell script is just cloning the oF repo then trying to mv  a projectGenerator directory into the openFrameworks/apps dir.

Looks like lines 4 & 5 in openFrameworks/apps/projectGenerator/scripts/linux/buildPG.sh are where things go wrong
```
git clone --depth=1 https://github.com/openframeworks/openFrameworks
mv projectGenerator openFrameworks/apps/
```
 cloning the oF repo from github means it doesn't come with the projectGenerator directory. Perhaps it means to clone the actual PG repo?

**Comment by arturoc** [comment]
what script are you trying to run? is not very clear from your explanation, can you detail the steps you are doing? Also have you checked the INSTALL_FROM_GITHUB.md guide? it explains all the steps to install OF from github

**Comment by drewLo** [comment]
Ah no, I hadn't seen INSTALL_FROM_GITHUB.md , I was just going off the main readme that stated projectGenerator had to be retrieved separately. using `projectGenerator -r -o"." examples` appears to have succeeded in generating all the example projects.
