### ISSUE TITLE
commandLine issues

### ISSUE THREAD

**Issue by arturoc** [openframeworks/projectGenerator#18]
in osx, from OF rooot:

```
apps/projectGenerator/commandLine/bin/projectGenerator -o /Users/arturo/Desktop/openFrameworks/ examples/addons/allAddonsExample
```

tries to create the project in:

```
project path is: /Users/arturo/Desktop/openFrameworks/apps/projectGenerator/commandLine/bin/examples/addons/allAddonsExample
```

and:

```
apps/projectGenerator/commandLine/bin/projectGenerator -o . examples/addons/allAddonsExample
```

fails to parse `.` as a directory
apps/projectGenerator/commandLine/bin/projectGenerator -o /Users/arturo/Desktop/openFrameworks/ examples/addons/allAddonsExample
```

**Comment by ofZach** [comment]
it looks like at least one thing is an issue with Path::current(), it's returning the binary path, not CWD as I would expect.  digging into it a bit more.

**Comment by ofZach** [comment]
even getcwd gives the binary path, not the path I'm in in the terminal.   this seems to work, however: 

    getenv("PWD")

so changing this line: 

     Path cwd = Path::current(); 

to: 

     Path cwd = getenv("PWD"); //Path::current(); 

solves I believe the first issue.  Looking at the second now....

**Comment by arturoc** [comment]
we can also try with: `std::filesystem::current_path()` `$PWD` is probably not defined in windows

**Comment by ofZach** [comment]
Cool I'll take a look at that

**Comment by ofZach** [comment]
when I run at the root of OF, I get: 

    Path::current:      
    /Users/zachlieberman/Documents/openframeworks/git/
    openFrameworks/apps/projectGenerator/commandLine/bin/

    std::filesystem::current_path():
    "/Users/zachlieberman/Documents/openframeworks/git/
    openFrameworks/apps/projectGenerator/commandLine/bin"

     getenv('PWD'): 
     /Users/zachlieberman/Documents/openframeworks/git/openFrameworks

for me, getenv("PWD") is the only one that seems to work....

**Comment by arturoc** [comment]
perhaps the command line app is setting the current path to something else?

**Comment by arturoc** [comment]
actuall osx is doing this in ofUtils line 295:

```
#ifdef TARGET_OSX
	#ifndef TARGET_OF_IOS
		char path[MAXPATHLEN];
		uint32_t size = sizeof(path);
		
		if (_NSGetExecutablePath(path, &size) == 0){
			std::filesystem::path classPath(path);
			classPath = classPath.parent_path();
			chdir( classPath.native().c_str() );
		}else{
			ofLogFatalError("ofUtils") << "ofSetDataPathRoot(): path buffer too small, need size " << (unsigned int) size;
		}
	#endif
```

which doesn't seem very correct, i guess it's used to set the correct data path but it shouldn't change the current directory

**Comment by arturoc** [comment]
also in case it helps, linux also uses the current exe dir to find data so apps can be run from anywhere but it doesn't change the current dir and instead returns:

```
return string(ofFilePath::join(ofFilePath::getCurrentExeDir(),  "data/"));
```

in defaultDataPath()

**Comment by ofZach** [comment]
ah interesting, I'll check this out...  I also was looking for something like that, but in the poco sources :)

**Comment by ofZach** [comment]
ok -- I'm a little bit worried about digging into / changing ofUtils before 0.9, since I know that code was put there for a good reason (at some point in OF's history we had issues where the app would have differing values for CWD, either in the .app or outside it, and I think that was an attempt to normalize that.  this might have been glut specific and I remember it even being an option in the app settings of the glut window).    But I think there's an easy fix -- at the start of the console app, right at: 

     commandLineProjectGenerator() 

all the paths seem right so a quick solution would be just to grab the value of the CWD then, and use that stored value throughout the app.  It works and feels like it solves this problem.  Maybe down the line we can look at a better OSX CWD resolution strategy ?

**Comment by ofZach** [comment]
see https://github.com/openframeworks/projectGenerator/pull/22 for an example of this other approach...

**Comment by ofZach** [comment]
@arturoc this is fixed, right?

**Comment by arturoc** [comment]
yep
