### ISSUE TITLE
projectGenerator simple compilation is broken right now in osx

### ISSUE THREAD

**Issue by arturoc** [openframeworks/projectGenerator#19]
https://travis-ci.org/openframeworks/projectGenerator/jobs/76854881

seems some of the last commits are breaking the build. The actual code is in the core repository so it's hard to track where it was broken.

**Comment by ofZach** [comment]
seems related to LibraryBinary ?  I'm not sure I understand how to read the travis output.  Is it compiling the xcode project file for pg Simple and failing?

**Comment by arturoc** [comment]
yes, it's just compiling the pg simple, seems to be a link error,
probably just a missing cpp in the project file? probably regenerating
the project will fix it

**Comment by ofZach** [comment]
should be fixed by https://github.com/openframeworks/projectGenerator/pull/20
