### ISSUE TITLE
C++ flag -mtune=native makes oF projects not compile for iOS

### ISSUE THREAD

**Issue by sourya-sen** [openframeworks/projectGenerator#198]
PG is adding cpp flag `-mtune=native` which is not supported by clang for iOS projects. Mojave 10.14.2, Xcode 10.1, iPad Pro.

The exact error is:
`clang: error: the clang compiler does not support '-mtune=native'`

Simply taking it out of the flags for the iOS project works. 

Can/should it be just removed from PG - or will it cause issues for native Mac apps? It's being generated here:
https://github.com/openframeworks/projectGenerator/blob/c8ddfe81542a5d50853b8694adde3c033f36a17d/ofxProjectGenerator/src/projects/xcodeProject.cpp#L157

**Comment by danoli3** [comment]
Was fixed 2019
