### ISSUE TITLE
command line compiles as .app, can we remove OF or simplify

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#2]
because we use OF, the command line tool has a ton of dylib and dependancies baked in.  It would be good to simplify things.  for the most part, OF is used for text manipulation and file manipulation, so this can be written in poco / straight c++.

if we remove OF, can we make this a simple executable on OSX ?

also, we can likely remove pugixml if we want to for poco's simple xpath support, which covers about 95% of what we need.

**Comment by ofZach** [comment]
I have fixed this by ripping out the executable and changing the way this is compiled on osx (removing fmod).  closing this issue.

**Comment by Daandelange** [comment]
For the record, I found a small bug: the shell script that copies the executable from the app didn't work in Debug Mode (only in Release).
Fixed in #14
