### ISSUE TITLE
[REQUEST] - better background color when generating new projects

### ISSUE THREAD

**Issue by lewislepton** [openframeworks/projectGenerator#211]
this is isn't anything that breaks. but I think that the generated background color could be better by being darker when generating a new project.

I think for learners, when creating shapes with no colors etc at first, it can be hard to see shapes right from the start. you can see that the circle is not perfect, but with a darker background, this makes it easier to see. the same with 3d objects as well. its easier on the eyes & you can see properly.
even more so if your shapes are smaller on screen

I set the background on grayscale to 60 & it feels right, because it not too dark. but just think its nicer for people starting out to have a project that generates something a bit darker & makes it clearer for people to see shapes.

a better experience in total ;)

I know we can set this anyhow with `ofBackground()`. but for folks starting out, they may not know that. so are stuck with this brighter & harder to see way

2d shape
<img width="1136" alt="Screenshot 2019-06-26 at 12 51 47" src="https://user-images.githubusercontent.com/11299322/60177721-85502980-9811-11e9-8841-bbeaa03f5e45.png">
<img width="1136" alt="Screenshot 2019-06-26 at 12 52 07" src="https://user-images.githubusercontent.com/11299322/60177720-85502980-9811-11e9-8dd7-0c772979805a.png">

3d shape
<img width="1136" alt="Screenshot 2019-06-26 at 12 53 38" src="https://user-images.githubusercontent.com/11299322/60177732-8f722800-9811-11e9-9122-26f79cd65c0a.png">
<img width="1136" alt="Screenshot 2019-06-26 at 12 53 59" src="https://user-images.githubusercontent.com/11299322/60177733-8f722800-9811-11e9-8f29-6b7045b783d2.png">

smaller shapes
<img width="1136" alt="Screenshot 2019-06-26 at 12 58 07" src="https://user-images.githubusercontent.com/11299322/60177958-24752100-9812-11e9-96b6-9fb3a01689ad.png">
<img width="1136" alt="Screenshot 2019-06-26 at 12 58 26" src="https://user-images.githubusercontent.com/11299322/60177955-24752100-9812-11e9-89e4-3fd4ca205cdc.png">

**Comment by ofZach** [comment]
this is a small but helpful change and I'd be supportive of this.  the idea we have always had is that the draw color should be white by default so images look correct, and this makes white look a lot better.

**Comment by ofZach** [comment]
Also, this isn't really an issue with the project generator but with OF generally -- can you open it there and close this?  The PG just copies template code but the part where the BG is set is in OF.

**Comment by lewislepton** [comment]
aye that's fine. I just posted here because since the projectGenerator... errr, generates it ;)

but ill repost it on the openFrameworks repo
