### ISSUE TITLE
Fix root path for macOS ( translocation / signing etc )

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#220]
Moving this issue over here: https://github.com/openframeworks/openFrameworks/issues/6395 

@bakercp @ofZach is the signing approach something we can do right now? 

I tried quickly to code sign locally but it didn't solve the issue. 
Also took a look here which has some helpful info: https://github.com/electron/electron-osx-sign/wiki/3.-App-Sandbox-and-Entitlements

**Comment by ofZach** [comment]
I think a signed disk image of OF (the whole folder) would work to fix this -- if you want to test, there's an app called DMG canvas which is what I use for clients to deal with app translocation and it let's you sign the dmg.

**Comment by ofTheo** [comment]
Ahh that makes sense. yes was just reading about that. 

Would it be easier to do a signed DMG for just the projectGenerator as the OF releases are packaged on linux, but I _think_ the PG is built on macOS?

I am guessing also the PG app might need to be notarized for 10.15 to run without issue?

**Comment by arturoc** [comment]
The PG is signed in the CI servers when built but having it as a DMG would require people to move it to the right place, i can see how some people would move it to apps or similar where it won't work as the PG relies on the OF folder structure to find the templates...

**Comment by ofZach** [comment]
agree, I think a dmg for the whole OF download (OSX) would make more sense vs forcing people to move the PG around -- there seems to be ways of making DMGs on linux, for example

https://askubuntu.com/questions/1117461/how-do-i-create-a-dmg-file-on-linux-ubuntu-for-macos

not 100% about signing...

**Comment by arturoc** [comment]
yes we are already signing the .app on linux in the CI server when building the PG

**Comment by arturoc** [comment]
actually no :) and there's no need cause the CI servers are osx. everything happens in this script: https://github.com/openframeworks/projectGenerator/blob/master/scripts/osx/buildPG.sh

**Comment by ofTheo** [comment]
Exploring options, this works with things as they currently are. 
Def not as elegant as a signed DMG for the macOS downloads, but its seems to work great. 
Needs to be chmod +x 

Add this file to the projectGenerator folder: 
`_runMeFirst.command`

```
#!/bin/sh
cd "$( dirname "${BASH_SOURCE[0]}" )"
xattr -r -d com.apple.quarantine projectGenerator.app
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/144000/66946697-5222e780-f006-11e9-852a-649d51a761ba.png">

It removes the quarantine flag and lets things work as desired.

**Comment by ofZach** [comment]
that's a simple fix :)   The text on the PG (which happens when its run in /tmp) could mention to run this.  Would people need to chmod it or does that get preserved across zip

**Comment by ofTheo** [comment]
@ofZach I think it would be preserved ( for apothecary +x seems to be preserved ). 

Was going to suggest renaming so its just for macOS users, but I think we could also just strip it out of the packaged downloads for other platforms.

**Comment by arturoc** [comment]
a cleaner way of doing this would be to call xattr from the electron app whenever it can't find the path once the correct path is given that way the next time is run it should have the attributes stripped

**Comment by ofZach** [comment]
worth testing!  I think I did try something like this in the past and it didn't work. 

* lots * of info here about bypassing etc
https://www.synack.com/blog/untranslocating-apps/

I still think ideal would be distributing OF with a signed DMG....

**Comment by ofTheo** [comment]
@arturoc had the same thought after doing that PR.  
There might be some funkiness with sandboxing though where you don't get the permissions needed to run xattr.  I'll see if I can get it working though. 

Also might look into the dmg thing for linux as that could be the better solution all-round.

**Comment by ofTheo** [comment]
Did a quick test. Can generate the dmg in linux fine, but no dice on the code-signing. 
I think we'd need a mac to do signing.  

Might look at the xattr from within the PG approach.

**Comment by micuat** [comment]
is this already fixed and documented somewhere? I saw a comment on Twitter that everyone encounters this issue when downloading a release. I don't fully understand how you fixed it, but if you need to manually run the script, it should be documented in the app or at least on ofSite
