### ISSUE TITLE
Older node version is breaking nightly builds

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#225]
I *think* this might be the cause nightly is breaking. 
https://github.com/openframeworks/projectGenerator/blob/master/frontend/package.json#L15 

```
"engines": {
    "node": ">=0.10.0"
  },
```

Even after updating node to 6.1 on the CI server it reverts back to an older version a few days later. 

```
Creating projectGenerator
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine har-validator@5.1.3: wanted: {"node":">=6"} (current: {"node":"4.8.7","npm":"2.15.11"})
npm WARN engine n-readlines@1.0.0: wanted: {"node":">=6.x.x"} (current: {"node":"4.8.7","npm":"2.15.11"})
module.js:327
    throw err;
```

Last time I fixed it by doing:
```
sudo npm install -g n
sudo n 6.11.0
```

But I am seeing the errors above again, making me think one of the scripts is reverting node somehow. 

Maybe when this is run its picking up the version from package.json?
https://github.com/openframeworks/openFrameworks/blob/7d4797f755f33f792951ea542773c8848e9d1f7c/scripts/dev/create_package.sh#L438 

Seeing as the node packages need >= 6 should we change: package.json to set 6.1 as the minimum? 
https://github.com/openframeworks/projectGenerator/blob/master/frontend/package.json#L15

**Comment by thomasgeissl** [comment]
we could use nvm (https://github.com/nvm-sh/nvm), specify the node version in `.nvmrc` (https://github.com/nvm-sh/nvm#nvmrc) and `run nvm` use before building it. Maybe `nvm install 6.11.0` is required before.

Probably also makes sense to update it a newer version. 6.11.0 is quite outdated.

I can have a look tomorrow.

**Comment by thomasgeissl** [comment]
```
export NVM_DIR="$HOME/.nvm" && (
  git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
  cd "$NVM_DIR"
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
) && \. "$NVM_DIR/nvm.sh"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm


nvm install 6.11.0
#nvm use 6.11.0
node -v
```

i havent had the time to test this. but executing this before you run `npm install && npm run build``` should download the right version and symlink it.

**Comment by ofTheo** [comment]
Thanks @thomasgeissl ! 
I am going to try first just changing the version in package.json and see if that fixes it. Just to avoid having one more dependency with nvm. 

Could I also just include these lines above `npm install`
Wouldn't this have the same effect?

```
npm install -g n
n 6.11.0
```

**Comment by ofTheo** [comment]
hmm not sure if #226 fixed it ( just ran on the server without error ) or there is something where building via the command line is getting a different set of env variables as building via crontab. 

Lets see...

**Comment by thomasgeissl** [comment]
i think setting the node version via any version manager before installing the dependencies should work. i would not rely on version specified in the package file. as far as i know, it will just throw a warning if you try to install a non compatible package (or an error if you set engine-strict in the config).

how is node currently installed?

**Comment by ofTheo** [comment]
So the issue actually is that when crontab is running nightly_build.sh it is not including the .profile which adds the user bin folder to the path.  I think I can fix this by loading the profile before running the nightly_build sh in the crontab. 

Thanks for your help debugging!

**Comment by ofTheo** [comment]
Nevermind still not working 🤦‍♂️
Going to try explicitly setting the version and see if that does anything.

**Comment by ofTheo** [comment]
Fixed. See https://github.com/openframeworks/openFrameworks/pull/6434#issuecomment-549964291
