### ISSUE TITLE
libPocoFoundation.so.64: cannot open shared object filee: No such file or directory

### ISSUE THREAD

**Issue by alexxcharr** [openframeworks/projectGenerator#239]
i recently installed openframeworks on arch linux. everything worked fine but now that i opened it again after a month when i try to create a project or open an old one using the project generator i get the error:
"projectGenerator: error while loading shared libraries: libPocoFoundation.so.64: cannot open shared object file: No such file or directory"

any suggestions why this could be happening?

**Comment by icq4ever** [comment]
I fixed this issue by recompiling projectGenerator with `scripts/linux/compilePG.sh`.
first, check make version of your system with `make -v` command, then if it `v4.3`, you need to downgrade to `v4.2.1`. 

you can use [downgrader AUR package](https://aur.archlinux.org/packages/downgrader/). 
then type `downgrader -a make`

hope this help.
