### ISSUE TITLE
pgLegacy won't compile on VS2015

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/projectGenerator#24]
pgSimple compiles and starts (I didn't test any actual functionality) without issue, but I get linking errors related to LibraryBinary for pgLegacy. I think whatever happened this commit https://github.com/openframeworks/projectGenerator/commit/3e412abe22c5a8030f909a65676c57433eacbfb0 needs to happen as well? That looks like a non-trivial reorganization so I don't want to muck things up...

The reason I'm bothering with pgLegacy rather than using the commandLine tool is that I can't add addons that are outside of OF_ROOT\addons, which I reported here https://github.com/openframeworks/projectGenerator/issues/23

**Comment by ofZach** [comment]
I think you need to add some files (that were added to the ofxProjectGenerator addon here: 

https://github.com/openframeworks/openFrameworks/tree/master/addons/ofxProjectGenerator/src/utils

it should be as simple as adding those files and then recompiling.  PRs welcome!

**Comment by mattfelsen** [comment]
Well that was embarrassingly simple -- the huge diff in the vcxproj file through me off! PR submitted :)
