### ISSUE TITLE
Project generator not included in qt creator / msys2 64bit download

### ISSUE THREAD

**Issue by tobiascornille** [openframeworks/projectGenerator#262]
I'm trying to use open frameworks, but I can't find the projectGenerator.exe file in the files I downloaded from [https://openframeworks.cc/download/](https://openframeworks.cc/download/)

**Comment by ofTheo** [comment]
Thanks for the report.
I think it should be fairly easy to add this. 

I'll need to add a line here for msys2:
https://github.com/openframeworks/projectGenerator/blob/master/frontend/index.js#L93

Then update the create package script in the main repo to include the compiled PG, but then it should all work. 🤞

**Comment by tobiascornille** [comment]
Thanks for the quick fix @ofTheo 
Any idea when this will be included in the download itself?

**Comment by ofTheo** [comment]
Hey @tobiascornille 

Once this is merged: https://github.com/openframeworks/openFrameworks/pull/6696 
It should start appear in the nightly builds. 

In the meantime you could always grab the PG folder from the VS download copy it into your msys2 OF folder and edit this file: https://github.com/openframeworks/projectGenerator/pull/263/files  if you need it sooner.
