### ISSUE TITLE
QTKit legacy issue that prevents submitting apps to the apple store (and a solution)

### ISSUE THREAD

**Issue by bvoq** [openframeworks/projectGenerator#264]
If you generate a project for macOS in the build settings of the xcodeproj the framework QTKit is still in OF_CORE_FRAMEWORKS.
The automatic verifier of the mac app store detects this as an issue and doesn't accept the code. 

<img width="1512" alt="framework_qtkitmakesitimpossibletosubmittoappstore" src="https://user-images.githubusercontent.com/3169217/112503765-7d793c80-8d8b-11eb-86a5-454aa1657e40.png">

![image](https://user-images.githubusercontent.com/3169217/112504331-f7112a80-8d8b-11eb-8ff8-f789ce3560b9.png)

The solution is to simply remove ```-framework QTKit``` from ```$OF_CORE_FRAMEWORKS``` in the build settings. I wanted to fork it, but I didn't find the entry in the code with a quick grep search. Cheers!

**Comment by dimitre** [comment]
Maybe it is time to phase out QTKit from OFW. 
There are always OFW legacy versions if somebody wants to use it for any reason.

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/6960
