### ISSUE TITLE
projects generated don't compile with msys2/mingw due to backslashes in config.make

### ISSUE THREAD

**Issue by Arithryka** [openframeworks/projectGenerator#265]
When I generate a project (or update an example project) with projectGenerator (with msys2/mingw platform selected) and attempt to compile it (using mingw64) I get "no such file or directory." Untouched examples compile fine. I found the culprit is that the OF_ROOT path in config.make files created by projectGenerator uses backslashes. Replacing them with forward slashes makes it work. msys2/mingw uses backslash as an escape character.
e.g.
does not work: `OF_ROOT = C:\Users\Arithryka\Documents\openFrameworks` (msys2/mingw sees this as C:UsersArithrykaDocumentsopenFrameworks)
works: `OF_ROOT = C:/Users/Arithryka/Documents/openFrameworks`

**Comment by ofTheo** [comment]
Thanks for reporting this. 
I think it should be a fairly easy fix. 

We added the PG Frontend for msys2 in 0.11.1 and I did test it on Windows, but somehow didn't run into this issue. 
I think it could be fairly easy to make sure the OF_ROOT uses forward slashes for msys2 in this line.

https://github.com/openframeworks/projectGenerator/blob/master/frontend/index.js#L727

**Comment by ofTheo** [comment]
tagging @dimitre 
maybe this is fixed with filesystem changes?

**Comment by ofTheo** [comment]
going to close this for now - I think mingw requires / for paths. so might not be a PG issue. 
@oxillo can you confirm?
