### ISSUE TITLE
Idea: modernize project.pbxproj reading/writing

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#280]
Latest XCode projects substitute PLIST/XML to JSON inside project.pbxproj
If we change the way PG writes XCode project to a more modern format it will be easier to modernize things, maybe even using XCode itself to update emptyExample template.

**Comment by 2bbb** [comment]
maybe, if we edit the template file on Xcode, then it will be saved as json-like format??

like:

```
// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 46;
...
```

(test on Xcode 12.4)

**Comment by 2bbb** [comment]
i think, simple way is loading pbxproj by `NSDictionary` and converting to json string with `NSJSONSerialization` in `xcodeProject.cpp`.

**Comment by 2bbb** [comment]
https://github.com/libimobiledevice/libplist
i found this library. i think this library is useful to make portable any env...?

**Comment by dimitre** [comment]
Nice. I think there are some tools for edit / create pbxproj files like this one
https://pypi.org/project/pbxproj/#files
or Cmake

Maybe there are others out there easier to integrate in projectGenerator.
PG now does all the heavy lifting editing directly the XML, if we use an external library to handle pbxproj hopefully PG becomes future proof for the time Apple decides to change the format again.

**Comment by dimitre** [comment]
@2bbb just found a builtin tool called PlistBuddy
It is built in in macOs and it can convert back and forth plist (xml) and dict (json)
You can invoke it with the absolute path
```
/usr/libexec/PlistBuddy
```
this article explains a little bit how it can be used
https://medium.com/@marksiu/what-is-plistbuddy-76cb4f0c262d

**Comment by dimitre** [comment]
It seem to handle quite well both old and new xcode format. 
```
/usr/libexec/PlistBuddy -c 'print' /Volumes/tool/ofw/apps/WerkApps/3dRoom2021/3dRoom2021.xcodeproj/project.pbxproj 
```

**Comment by dimitre** [comment]
this is a WIP to replace all pugi::xml to PlistBuddy
https://github.com/dimitre/projectGenerator/blob/buddy/ofxProjectGenerator/src/projects/xcodeProject.cpp

**Comment by 2bbb** [comment]
hi, @dimitre 

I think PG needs to process xcodeproj in advance mode.
can we use PlistBuddy on multiplatform?

**Comment by dimitre** [comment]
this is the downside: it wont work multiplatform.

**Comment by 2bbb** [comment]
right...

I hadn't noticed `libplist` doesn't support JSON-like format.
and I can't find the cross-platform plist (or only pbxproj) parser.

however I find this [ https://github.com/liaogang/xcpjParser/ ], this code is not well maintained, but this helps us...?

**Comment by dimitre** [comment]
I'm still try to complete my fork using PlistBuddy even if it is not a replacement.
it is great to be able to work without xml editing there, and I personally never had to generate an xcode project from linux for example.

**Comment by dimitre** [comment]
I've just finished plistBuddy fork here. 
https://github.com/dimitre/projectGenerator/tree/buddy
I still have some testing to do, it is working great with the addons I've tested here.

I've removed all the traversing done previously in pugi::xml so it is just children being added from the parent.
So I think it is easy to port to some other tool too

This function gets the UUID for any folder. if the folder is already added then it returns its UUID stored in a map.
if the file doesn't exist it creates one UUID for each parent folder (addons / ofxMidi / src) and link them automatically

https://github.com/dimitre/projectGenerator/blob/70e299b1107240cf68f9a2ef2c537dcac348b53d/ofxProjectGenerator/src/projects/xcodeProject.cpp#L187-L227

**Comment by 2bbb** [comment]
@dimitre

I totally agree to what you say "I personally never had to generate an xcode project from linux for example".
but, we need to think about advanced mode.

I think, best way is search or development multiplatform plist parser... but... 😔

**Comment by dimitre** [comment]
still searching for libraries that help parsing / writing plist files
https://github.com/microsoft/PlistCpp/tree/master/src
https://github.com/animetrics/PlistCpp

**Comment by dimitre** [comment]
@2bbb I finally found a nice solution for an easy parsing of xcodeproject. I found plist is acceptable too in json format, and we can convert using:
```
plutil -convert json /Volumes/tool/ofw/scripts/templates/osx/emptyExample.xcodeproj/project.pbxproj 
plutil -convert json /Volumes/tool/ofw/scripts/templates/ios/emptyExample.xcodeproj/project.pbxproj 
```
After this it is very easy to set values using built in nlohmann::json
and using Json Pointers to set string values and append arrays, like
```
/objects/E4B69B610A3A1757003C02F2/buildSettings/HEADER_SEARCH_PATHS/
```

**Comment by dimitre** [comment]
Closed by https://github.com/openframeworks/projectGenerator/pull/295
