### ISSUE TITLE
Nightly builds macOS : projectGenerator should be recompiled

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#300]
projectGenerator electron has to be rebuilt to be working with latest commandLine

**Comment by ofTheo** [comment]
Hmm - I thought we were building and uploading it via the Github Actions workflow. 
Will take a look!

**Comment by ofTheo** [comment]
The issue was I had to sign the Mac Developer Agreement again. 🤦‍♂️
Should be good now. 

We should update the zips though for msys2 and vs.
