### ISSUE TITLE
Compiling projectGenerator on Visual Studio 2022 fails with not finding header files.

### ISSUE THREAD

**Issue by mscherotter** [openframeworks/projectGenerator#304]
Compiling the projectGenerator on Microsoft Visual Studio 2022 causes these errors?
What is the dependent library for GL/glew.h?

1>d:\source\repos\openframeworks\libs\openframeworks\utils\ofconstants.h(130): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory (compiling source file ..\..\..\openFrameworks\utils\ofUtils.cpp)
1>d:\source\repos\openframeworks\libs\openframeworks\utils\ofconstants.h(130): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory (compiling source file ..\..\..\openFrameworks\utils\ofXml.cpp)
1

Thanks,
Michael

**Comment by ofTheo** [comment]
Hi - I think you might be missing the OF libs/dependencies. 

The easiest way to run OF is to use the nightly builds which package the main repo, with the PG repo and the 3rd part libs. 
https://openframeworks.cc/download/ ( nightly builds at the bottom of the page ) 

For more info on working in the repos instead see: 
https://github.com/openframeworks/openFrameworks#readme

Going to close this but please let me know if, it is in fact in issue on our end.
