### ISSUE TITLE
projectGenerator doesn't include other files in src/ folder

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#306]
In the nightly builds the `multiWindowExample` is missing guiApp.h and guiApp.cpp from `src/` in the Xcode project. 
I think this might be a new regression from the json switch. cc @dimitre 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/144000/190700440-5cf3dbd6-0e37-466a-9699-a795214d850d.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/144000/190700494-9bcaa99e-0fb0-4b58-8ad9-4ac949a61082.png">

**Comment by dimitre** [comment]
This is working great here with projectGenerator latest and OF latest.
please double check if you are using openframeworks latest or some fork (I use to use my own forks in a day to day work to avoid commiting in the wrong place)

**Comment by dimitre** [comment]
<img width="273" alt="Screen Shot 2022-09-16 at 15 46 27" src="https://user-images.githubusercontent.com/58289/190710001-8c077fe5-c3a8-4696-a5e9-fd1619afd852.png">

**Comment by ofTheo** [comment]
Apologies @dimitre - I think I used the nightly from the day before the example generation fixes you did. 
No issue here 🤦‍♂️🙂
