### ISSUE TITLE
color output leads to weird console logs

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#31]
I'm seeing this everywhere now : 

     ←[1m←[31m

ie: 

     updating project C:\Users\zach\Desktop\openFrameworks\apps\myApps\myWarmSketch
     ←[1m←[31mofFile: remove(): 

when there is a warning or error.   I believe this is related to: 

https://github.com/openframeworks/projectGenerator/blob/master/commandLine/src/main.cpp#L41-L59

can we maybe disable this for OSX and windows?   It's also going to cause issues with the gui since it captures the results of feedback and reports it back (and these color commands come out as text)

**Comment by arturoc** [comment]
i can add a command line option to remove it, that way people running it from the command line will see the colors in the output but the gui won't get the weird characters

**Comment by ofZach** [comment]
it doesn't work at all on osx or windows for me -- can it be opt-in vs opt-out ?   or set via an env variable?

**Comment by arturoc** [comment]
mmh, that's the same color codes that we have in apothecary which dan i suppose did in osx. but we can remove them completely by now if they are problematic.
