### ISSUE TITLE
json error breaking nightly builds

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#313]
Hey @dimitre - I think this might be related to the recent changes ( sometime between 10/19 and now ). 
It is breaking the nightly builds 

```
Recompiling command line PG
                    
Creating project files for ios
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '/'
```

**Comment by dimitre** [comment]
Allright! I'll check it soon

**Comment by dimitre** [comment]
here. ios template was not in json format
https://github.com/openframeworks/openFrameworks/pull/7148/files

**Comment by ofTheo** [comment]
Thanks @dimitre! 🙏

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/openFrameworks/pull/7148
