### ISSUE TITLE
A JavaScript error won't let projectGenerator.exe to even run

### ISSUE THREAD

**Issue by AgustinVallejo** [openframeworks/projectGenerator#316]
Hello, I get this error as soon as I open the projectGenerator :/ I'm not really familiar with these installations, any idea?

![image](https://user-images.githubusercontent.com/37052186/212564403-f7ae16af-c389-4814-810e-127bc6edfd5c.png)

**Comment by ofTheo** [comment]
I wonder if it’s an issue with the accent in the username? 

Could you try moving the OF folder out of your Users directory and into the root of C: ? 

If that’s the issue we should find a fix for it. 

Thanks!

**Comment by AgustinVallejo** [comment]
@ofTheo That seemed to be the problem, moved to ProgramFiles and it now works. Thanks!
