### ISSUE TITLE
Windows VS projects broken in nightly 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#329]
Looks like the latest PG is generating relative paths for VS ( and maybe other projects? ) missing the trailing slash from the relative OF_ROOT path. 

Notice the lack of / before libs: 
`../../..libs\openFrameworksCompiled\project\vs\openFrameworksDebug.props` 

This might also be the issue behind #327

**Comment by ofTheo** [comment]
the  files affected seem to be the vcxproj file for the example and the .sln file. 
the above error is the vcxproj file and in the sln file the error is: 

`Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "openframeworksLib", "..\..\..libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj"` 

note the ..\..\..libs should be ..\..\..\libs

**Comment by dimitre** [comment]
this piece of code of actual project generator doesn't makes sense
```c++
	std::string relRoot = getOFRelPath(ofFilePath::removeTrailingSlash(projectDir));
 	if (relRoot != "../../../"){
```
because the condition is always fail and the block will always execute.

**Comment by ofTheo** [comment]
@dimitre yes - that's exactly the issue I think. 
relRoot is missing the trailing slash. so it is always false.  add a trailing slash to getOFRelPath and I think this fixes everything.

**Comment by dimitre** [comment]
ok I've updated the PR

**Comment by ofTheo** [comment]
cool - if this passes the checks then I can try and regenerate the nightly packages and we can see if it fixes things. 
I think it might end up fixing a bunch of other small bugs too. 

this FS stuff is def pretty tricky 🙂

**Comment by dimitre** [comment]
Yes in fact pure FS is super ok.
but all the string work needed before, mixed with FS is indeed tricky :)

**Comment by ofTheo** [comment]
cool - VS looks good just from looking at the regenerated nightly files. 
going to try actually building the project on my slow pc laptop for confirmation but I think this is fixed.  👍

**Comment by ofTheo** [comment]
just ran the nightly VS build and it works now.  
thanks @dimitre @nickhardeman
