### ISSUE TITLE
adding ofxOsc with project generator adds win32 folder

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#35]
I created a project with the new project generator, and added ofxOsc. It added the win32 folder to the project, which causes Xcode to complain winsock2.h not found.

**Comment by thomasgeissl** [comment]
The same happened to me.
Makefiles on OSX work fine.

**Comment by arturoc** [comment]
which version are you using? i remember fixing this after the 0.9RC

**Comment by thomasgeissl** [comment]
osx 10.10, 
pg: 592b4d35aecc00e3cf5acf74b972d695a8f5744d,
oF: 9b884b68dd6001562fcb382fb3caa50054904ed7

Sorry, I guess that I just haven't rebuilt it correctly. 
I am in the train right now and cannot build the project generator. I will tell you later.

**Comment by thomasgeissl** [comment]
I just cloned the repo and did ```npm install``` and ```npm start```. It still added win32 directory. Do I miss an important step?
```npm run build``` did not work.

**Comment by arturoc** [comment]
not sure. you can get the very last version from the nightly builds

**Comment by thomasgeissl** [comment]
The most recent version from the nightly builds worked fine for me. But if I clone this repo and run ```npm install```and ```npm start``` it does not.
Is there any caching involved when compiling?

**Comment by arturoc** [comment]
apart from building the electron gui you need to rebuild the binary for the command line app and put it in the right folder, it might be that the app there is still old. we should probably just delete the binary from the pgElectron project and have a script or something that does the right thing which is also called from the package creation script

**Comment by thomasgeissl** [comment]
Okay, that was the important step I was missing. I agree that a script which compiles and moves the command line app would simplify the process a little.
