### ISSUE TITLE
PG example gen is naming projects based on two folders up - not parent folder

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#351]
Kinect example is named computer_vision 

![image (31)](https://user-images.githubusercontent.com/144000/232921371-6c3277aa-f7da-441a-a84d-2d18147b57f4.png)

3DPrimitivesExample is named 3d

![image (32)](https://user-images.githubusercontent.com/144000/232921474-0f394ddf-f817-4a1d-8a60-3e7313169baa.png)

**Comment by ofTheo** [comment]
My guess here is that its this line:
https://github.com/openframeworks/projectGenerator/blob/master/commandLine/src/projects/baseProject.cpp#L124 

And an issue with no "/" at the end of the path. 

With a path being `examples/3d/3DPrimtivesExample` parent_path becomes 3d
If the path like `examples/3d/3DPrimtivesExample/` parent_path becomes 3DPrimtivesExample

Just a guess.

**Comment by dimitre** [comment]
Ok! did you create this projects recursively? or one by one? I suppose it is a windows only issue since I'm getting correct project names in macos right? I'll try to figure out what is going on

**Comment by ofTheo** [comment]
Yes recursively. It was actually the nightly build script just doing it’s normal thing. ( running on Linux but making the windows project files ). 

Maybe it’s an issue on Linux but I’ll check the macOS nightly and see if that one is similar.

**Comment by dimitre** [comment]
Thanks, I'm downloading the nightly now. I think it may be something specific to 
```bool visualStudioProject::createProjectFile()```
will check soon

**Comment by dimitre** [comment]
ok solved here. PR soon

**Comment by dimitre** [comment]
Answering your first comment, the line you pointed out is right but my logic was wrong. there is no parent_path needed only filename, and this doesn't depend of trailing slash. the beauty of fs::path is it totally abstracts slashes

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/projectGenerator/pull/352
