### ISSUE TITLE
project generator replaces dashes with underscores

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#36]
(copied from https://github.com/openframeworks/openFrameworks/issues/4361 )

i sometimes use dashes in my project names and the pgElectron interface seems to replace them with underscores when i try to update the project file, which means it fails to open the addons.make correctly, and also generates new source files.

maybe a better behavior would be to throw an error when trying to import something rather than automatically replacing it with underscores?

**Comment by ofZach** [comment]
for reference this is happening here: 

https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorElectron/app.js#L420-L422

feel free to test changes to this, I think spaces, commas and path seperators will be problematic but other stuff should be ok.

**Comment by bakercp** [comment]
This is problem we encountered in class today -- we were trying to regenerate project files for ofxCv, which uses dashes and it was doing some funky stuff.

This used to also be an issue with the windows project generator -- generally it seems like we should allow dashes and underscores no?

**Comment by ofZach** [comment]
I've changed this here: 

https://github.com/openframeworks/projectGenerator/commit/4460cecccc5feffe15a98c2b31996ed3a2eb6ad5

I'm now altering the following characters: 

``` & / \ # , + ( ) $ ~ % .. ' " : * ? < > { }```

but leaving the dashes fine.  Just tested a project but invite more testing...

**Comment by bakercp** [comment]
:+1: Thx!  Will check it out.

**Comment by ofZach** [comment]
I think this is fixed, going to close this, feel free to reopen...
