### ISSUE TITLE
Wrong paths for addons on XCode on latest nightly builds

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#368]
In XCode examples, the ones who uses addons
The files are correctly linked but the folders are not, and are appearing as red.

![Screen Shot 2023-05-02 at 13 00 22](https://user-images.githubusercontent.com/58289/235720945-b4a974fb-91b2-44b0-a1cd-731b8c1ef7c2.png)

But I'm testing with the latest projectGenerator and it is including folders correctly.

**Comment by dimitre** [comment]
I've just tried to test using the recursive command line like this one
```
./projectGenerator.app/Contents/MacOS/projectGenerator  --recursive -posx -o../../../../ ../../../../examples
```
and it works correctly. 
so maybe it is a Linux issue, I can look at this. 
Is the script checking out projectGenerator latest? and which command does it use to generate the examples projects?

**Comment by ofTheo** [comment]
one more possibility - maybe OF master needs PG to be updated to latest?

**Comment by dimitre** [comment]
Yes maybe another possibility
I've opened an Ubuntu here, pulled OF and PG to latest, compiled PG, used commandLine recursively to generate XCode and transferred here via Rsync and addon paths are OK here.

**Comment by 2bbb** [comment]
same problems are happen on my mac when I test external source path.

my pg frontend's verbose outputs (added some line breaks):

```
(command used: /Users/2bit/prog/of/openFrameworks/apps/projectGenerator_dev/frontend/app/projectGenerator
  -v
  -o"/Users/2bit/prog/of/openFrameworks"
  -a" "
  -p"osx"
  -s"/Users/2bit/prog/of/openFrameworks/apps/myDevApps/mySketch/src,/Users/2bit/prog/of/openFrameworks/apps/myDevApps/arcfix/src" -t"" "/Users/2bit/prog/of/openFrameworks/apps/myDevApps/myAutomaticSketch")
```

and

```
[notice ] project path is: "/Users/2bit/prog/of/openFrameworks/apps/myDevApps/myAutomaticSketch"
[notice ] setting up new project "/Users/2bit/prog/of/openFrameworks/apps/myDevApps/myAutomaticSketch"
[notice ] updating project "/Users/2bit/prog/of/openFrameworks/apps/myDevApps/myAutomaticSketch"
[verbose]  adding file /Users/2bit/prog/of/openFrameworks/apps/myDevApps/mySketch/src/ofApp.cpp in folder mySketch/src to project 
[verbose]  adding file /Users/2bit/prog/of/openFrameworks/apps/myDevApps/mySketch/src/ofApp.h in folder mySketch/src to project 
[verbose]  adding file /Users/2bit/prog/of/openFrameworks/apps/myDevApps/mySketch/src/main.cpp in folder mySketch/src to project 
[verbose]  adding search include paths for folder ../mySketch/src/
[verbose]  adding file /Users/2bit/prog/of/openFrameworks/apps/myDevApps/arcfix/src/ofApp.cpp in folder arcfix/src to project 
[verbose]  adding file /Users/2bit/prog/of/openFrameworks/apps/myDevApps/arcfix/src/ofApp.h in folder arcfix/src to project 
[verbose]  adding file /Users/2bit/prog/of/openFrameworks/apps/myDevApps/arcfix/src/main.cpp in folder arcfix/src to project 
[verbose]  adding search include paths for folder ../arcfix/src/
```

but in Xcode:

<img width="268" alt="スクリーンショット 2023-05-05 7 20 35" src="https://user-images.githubusercontent.com/200899/236341973-05b2bfa5-072a-4d86-8350-52d2bcd2040e.png">

<img width="252" alt="スクリーンショット 2023-05-05 7 20 30" src="https://user-images.githubusercontent.com/200899/236342001-d5aed7c2-3437-4dbd-827a-551ba1803d37.png">

does feature of resolving to relative path is broken?

**Comment by 2bbb** [comment]
I tested with adding ofxOsc, then addon directory was added correctly.

**Comment by dimitre** [comment]
I'm starting to investigate the issue now, and the first thing I'll be probing out is if the latest projectGenerator commandLine is the one being bundled in projectGenerator frontend.
for now I've submitted a PR to disable caching in macos, updating the script to clone a fresh OF copy, and the third one is outputting to terminal a temporary version number I'll be using only to debug, and can be removed later (v001)

I'll be mergin this one as soon as it passes the tests
https://github.com/openframeworks/projectGenerator/pull/370

@ofTheo can the release nightly action be triggered manually to test?

**Comment by ofTheo** [comment]
It can! 🙂
It’s called manual nightly and you can run it from the Actions tab.

**Comment by dimitre** [comment]
Ahh I don't have access to this one. Can you please run manually anytime? I've already merged.
Only if you still have access to your computer, if not we can check this out when you're back

**Comment by ofTheo** [comment]
@dimitre - just started it. 
You should have access to it now - let me know if you don't see it 🙂

**Comment by dimitre** [comment]
Great! I still don't see the action, here is my view.
<img width="525" alt="Screen Shot 2023-05-05 at 21 22 28" src="https://user-images.githubusercontent.com/58289/236588096-3f6acf52-f97f-419f-880b-60dde2e0cfc4.png">

Thanks I'm now using PG frontend with the latest here, already testing everything

**Comment by ofTheo** [comment]
@dimitre its in OF/OF 🙂
https://github.com/openframeworks/openFrameworks/actions/workflows/manual-nightly.yml  

That's where all the packaging happens for the nightly builds including the PG frontend. 
We should prob do the packaging locally in PG repo but that was just how it was done before.

**Comment by dimitre** [comment]
Yess all there! thank you!

**Comment by ofTheo** [comment]
the nightly in this repo is updated on any PR update - just  called nightly for now

**Comment by ofTheo** [comment]
so that var is set by this line:
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh#L126 

which is the `openFrameworks_pkg_creation` folder the repo is cloned into 
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/create_package.sh#L114

For the nightly builds this is all inside of openFrameworks/out
https://github.com/openframeworks/openFrameworks/blob/master/scripts/ci/package_builds.sh#L14 

so something like `openFrameworks/out/openFrameworks_pkg_creation`
