### ISSUE TITLE
in osx, local add-ons are ignored because they don't seem to exist (but they do) 

### ISSUE THREAD

**Issue by lmtanco** [openframeworks/projectGenerator#372]
Hi there! 
I am working with the nightly v20230524_osx version of Project Generator. 
My local add-ons are correctly read by project generator out of addons.make: 

![image](https://github.com/openframeworks/projectGenerator/assets/1093084/4b92c750-d2e9-4720-b8c5-82cacc6ce7c9)

However, later they are ignored (and addons.make is actually modified  to delete all ignored addons): 

![image](https://github.com/openframeworks/projectGenerator/assets/1093084/76f992b5-660e-4973-ae56-eb477e0bb80b)

But I am sure they do exist! 

I would like to help debugging this but not sure how to build a debug version of projectGenerator on macOS. 

My configuration is: 

- of_v20230524_osx_release
- macOS Ventura 13.3.1 (M2 Pro)

Many many thanks for any help! 

Luis.

**Comment by dimitre** [comment]
I'll work on this issue later but for now can you try the same thing renaming "addons" folder to another name? any other name will do, like local_addons. let me know if it works or still fail

**Comment by roymacdonald** [comment]
Hi, same here. The name of the folder does not matter. This is a huge deal breaker for me as lots of my projects rely on local addons. I see that there have been a lot of changes regarding paths and etc. Not sure why this was done but the way it was before worked well. 
I can help with this. @dimitre can you please point out where to start looking at?

**Comment by lmtanco** [comment]
Thanks! Just to confirm @roymacdonald, renaming "addons" did not help.

**Comment by 2bbb** [comment]
@dimitre
thanks to mention.
i will debug soon!

**Comment by 2bbb** [comment]
I tested frontend with local addons directory.

`addons.make` is

```
ofxOsc
./addons/ofxPubSubOsc
```

and results console out is:

```
(command used: /Users/2bit/prog/of/openFrameworks/apps/projectGenerator_dev/frontend/app/projectGenerator -v -o"/Users/2bit/prog/of/openFrameworks" -a"ofxOsc,./addons/ofxPubSubOsc" -p"osx"  -t"" "/Users/2bit/prog/of/openFrameworks/apps/myDevApps/pgLocalAddonsDev")
```

is this wrong behavior of frontend...? `-a` options is seems to correct I think.

**Comment by roymacdonald** [comment]
@2bbb Thanks !.
does that command work? I mean does it generate the correct xcode project? (or whatever project)?
Do you get the same output if instead of `./addons/ofxPubSubOsc` it is `./local_addons/ofxPubSubOsc`, `../local_addons/ofxPubSubOsc` or `../whatever_folder_name/ofxPubSubOsc`? The folder names should not matter. Actually on windows there is a folder called `addons` generated in a projects' root folder which is esentially the build directory. Having a folder named like that for local addons could get nasty. Just saying

**Comment by 2bbb** [comment]
this command doesn't make correct project file.
I got error message like below. (got same message if folder name is `addons`)

```
[verbose] Ignoring addon that doesn't seem to exist: ./local_addons/ofxPubSubOsc
```

and, I tested with PG from v0.11.2 release zip and same `addons.make` and local addon structure, then PG frontend logged command:

```
"/Users/2bit/prog/of/v0.11.2_osx/projectGenerator/projectGenerator.app/Contents/Resources/app/app/projectGenerator" -v \
  -o"/Users/2bit/prog/of/v0.11.2_osx" \
  -a"ofxOsc,./local_addons/ofxPubSubOsc" \
  -p"osx" \
  -t"" \
  "/Users/2bit/prog/of/v0.11.2_osx/apps/myApps/pgLocalAddonsDev"
```

and I got correct xcode project file.

but both `-a` options are same.
so, maybe frontend is not wrong and commandLine binary is broken.

**Comment by 2bbb** [comment]
https://github.com/openframeworks/projectGenerator/blob/a658f136328e95e62f9b6c4569ed2a3b765e9264/commandLine/src/projects/baseProject.cpp#L265-L271

I fixed those lines to:

```cpp
	fs::path addonPath { addonName };
	auto joinedPath = addon.pathToProject / addonPath;
	if (fs::exists(joinedPath)) {
		addon.isLocalAddon = true;
	} else {
```

then, PG found local_addons. but, file browser in Xcode get wired behavier:

<img width="267" alt="スクリーンショット 2023-05-26 15 05 48" src="https://github.com/openframeworks/projectGenerator/assets/200899/690c314c-1fba-4e8d-b2db-325eadbc8ed2">

I think problem is on using `fs::exists` with project directory based relative path.

**Comment by 2bbb** [comment]
https://github.com/openframeworks/projectGenerator/blob/a658f136328e95e62f9b6c4569ed2a3b765e9264/commandLine/src/projects/baseProject.cpp#LL121C11-L121C14
https://github.com/openframeworks/projectGenerator/blob/a658f136328e95e62f9b6c4569ed2a3b765e9264/commandLine/src/main.cpp#L446

what are we expecting to be get by those 2 calling of `current_path()`?
`current_path()` returns cwd of executing envs, is it okay?
don't we need to set current path to "of path" or "project path"?

**Comment by dimitre** [comment]
Thanks @2bbb I'm now travelling and I will have a linux computer to test after May 30

**Comment by dimitre** [comment]
Hello @lmtanco @2bbb @roymacdonald  can you please test it again using the latest projectGenerator from here?
https://github.com/openframeworks/projectGenerator/releases
Thank you!

**Comment by roymacdonald** [comment]
Many thanks @dimitre 
Just tested it. 
It works but with some odd issues,

the addons.make file I used is 
```
ofxGui
ofxPoco
../../myApps/local_addons/ofxAvCodec
/Users/roy/openFrameworks_v0.11.2/addons/ofxSyphon
```
I was using this on OF's github master so the syphon entry is actually on a path outside of the OF path from the perspective of the project generator.

In xcode It adds the addons into the project under the same folder structure that the addons.make file has.

![Screen Shot 2023-07-27 at 17 39 36](https://github.com/openframeworks/projectGenerator/assets/974878/4717f937-cfd7-4b00-9558-8645e7b83cd6)

Notice that there are folders for each folder in the path. In the case of the absolute path it gets a bit annoying having to expand all in order to get to the files. Before the addons were simply put in a folder named local_addons. 
Also, notice that the syphon addon has its framework added on a different folder as the rest of the addon.

So, instead of using the whole string from the addons.make file to place the addon within the project, it should simply use the addon's name. if it is a local addon, it goes into the local_addons folder of the project, otherwise into addons.

**Comment by roymacdonald** [comment]
It is really nice to see that the dylibs are added into the project and copied to the executable :)
but it would be better to have those either inside a folder within the addon that added those or just a folder for all of em, just to unclutter the project navigator.

**Comment by dimitre** [comment]
Yes the dylibs were meant to be inside the addon. it is part of the local addons issue.
I'll test with paths similar to yours to see how to treat internal paths.

**Comment by dimitre** [comment]
Yes dylibs inside the executable will be great, but some of them will have to be updated, maybe with a script to change paths inside the dylib itself, like ofxHapPlayer which doesn't work at the moment, as it is

**Comment by dimitre** [comment]
other question about your addons.make. are you using your project two folders up from OF path? like ofPath = "../.." ?

**Comment by roymacdonald** [comment]
> Yes dylibs inside the executable will be great, but some of them will have to be updated, maybe with a script to change paths inside the dylib itself, like ofxHapPlayer which doesn't work at the moment, as it is

it is putting the dylibs automatically into the app. :)

> other question about your addons.make. are you using your project two folders up from OF path? like ofPath = "../.." ?

No, those paths are relative to the project folder, not the OF path. 

In simple terms, a local addon should not be treated at all differently than a regular addon. THE only difference should be that the local_addon is placed inside a folder in the project navigator called local_addons, while "regular" addons go in a folder named addons. All the rest should be exactly the same. 

Then also the paths to the addon should only be absolute when it is an absolute path in the addons.make file. 
(actually absolute paths are the least useful to me, as it does not allow sharing the project)

**Comment by dimitre** [comment]
@roymacdonald I've fixed the local_addons path, 
the new download will be ready after this action finishes
https://github.com/openframeworks/projectGenerator/actions/runs/5686237331

**Comment by dimitre** [comment]
@lmtanco I think this is fixed now. can you please test again using latest nightly?
Thank you

**Comment by lmtanco** [comment]
Hi!

Sorry @dimitre, I was on holidays. 

I've tested and the project looks great, see image. 

I have also taken a bit longer to answer because I am not 100% sure what is doing with the libraries - at the moment the project doesn't link. I will report back if 1) I figure it out and 2) I am sure it's not my fault. 

For the moment I am closing the issue if that's ok with everyone. 

Thank you very very much! 

Luis. 

<img width="979" alt="image" src="https://github.com/openframeworks/projectGenerator/assets/1093084/7e638954-00dd-4044-a53b-4686d7664114">

**Comment by dimitre** [comment]
Thanks @lmtanco.
If you find any issue with addons please open a separate issue with instructions of how to reproduce.
