### ISSUE TITLE
Project Generator frontend - OSX 13.3.1 (a) Not Responsive 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#376]
Mirroring @nickhardeman's issue here: 
https://github.com/openframeworks/openFrameworks/issues/7556 

I can reproduce it on my setup. 
Moving  the app outside of the `projectGenerator` folder and then back fixes the issue (as before) but I no longer get the warning to do that and the app is not responsive until I move it ( moving the app undoes the sandboxing/translocation ). 

So fix would be to make sure the 'running on macOS ... for  first time' dialog appears quickly on launch

**Comment by ofTheo** [comment]
Also possibly related, we're not building a universal app for the projectGenerator right now its x64 only. 
Going to try building a universal build and see if that makes it more responsive.

**Comment by 2bbb** [comment]
maybe we need trick if we use `electron-packager`.
https://github.com/electron/electron-packager/issues/1226

and maybe `electron-builder` has option for universal binary.
https://developer.mamezou-tech.com/blogs/2022/04/04/build-intel-m1-electron-app/ (sorry, this is japanese article...)

**Comment by ofTheo** [comment]
Yeah, I have it building with: `--arch=universal` but I get hung up on: 

`Detected file "Contents/Resources/app/app/projectGenerator" that's the same in both x64 and arm64 builds and not covered by the x64ArchFiles rule: "undefined"`

In theory you should be able to set x64ArchFiles to `Contents/Resources/app/app/projectGenerator` and it should ignore the duplicate binary ( which is already universal ), but there is almost not documentation on how to do that, and there is a good chance electron-packager isn't actually passing on that variable to the electron/universal package its using. 

I added to the issue here:
https://github.com/electron/electron-packager/issues/1226#issuecomment-1634544603 

Maybe a different packager could solve it?

**Comment by ofTheo** [comment]
Okay I have a universal build now the UI loads quicker now for M1 but the translocation is still making the app unresponsive. 
Everything works great once you move it up a folder and move it back but this is going to throw a lot of people off. 

We definitely need a splash screen explaining what to do if not translocated or if the OF path is not found.

**Comment by ofTheo** [comment]
closed by #387
