### ISSUE TITLE
behavior of addon selector varies depending on interaction

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#38]
there are five different different behaviors, depending on seven or so ways you can interact with the addons selector.

first, click on the addons field, type "ofxCv". then either:

1. hit "enter" or type a comma. "ofxCcv", a different addon, is selected. not sure why. or...
2. hit "space" or type a semicolon. the addon is not added, and if you type anything else it says "no results found". i would expect these to act more like typing a comma.
3. click anywhere else in the window. "ofxCv" exists as text but will not be included as an addon.
4. hit "tab". same as above, except you are now in the "platforms" field. even with "advanced" mode unchecked it's possible to delete the default platform, add non-existent platforms (and you can't un-delete it).
5. click on the addon name from the dropdown. the addon gets added, but the text also remains in addons field.

it looks like there are two desired behaviors: add an addon from the list, and leave the text you typed in the field until you select an existing addon. but they're getting a bit mixed up. the "platforms" menu seems a little more consistent in how it handles these.

**Comment by ofZach** [comment]
FYI, we didn't really code any of this stuff -- it's part of semantic-ui.  I don't know how much control we have over any of this, and it might be helpful to compare semantic-ui default behavior to this app: 

http://semantic-ui.com/modules/dropdown.html

see esp "Multiple Selection" and see if there's any issues that might be better filed there?

**Comment by kylemcdonald** [comment]
aha! i looked at it (assuming you mean "Multiple Search Selection"), and it definitely explains a lot of this behavior. but maybe we're behind a version or have made modifications? because there are a two things that are unexplained:

1. typing "idaho" does not match "idao" (unlike ofxCv and ofxCcv).
2. typing "cali" then clicking "california" does not leave the "cali" text in the box.

**Comment by ofZach** [comment]
it looks like there was a new version of semantic-ui since this was done, I'll take a look...

**Comment by kylemcdonald** [comment]
one more strange behavior to watch out for: if you hit space then enter, it will add your first available addon from the addon list. maybe related to the "ofxCv"/"ofxCcv" behavior?

**Comment by ofZach** [comment]
the searching is improved now via these option changes: 

https://github.com/openframeworks/projectGenerator/commit/abe207c293fc2f3c4cbc6d2f14aa01cd6dfb69d4

<img width="457" alt="screen shot 2015-10-18 at 10 31 23 pm" src="https://cloud.githubusercontent.com/assets/142897/10568567/084aaa22-75e8-11e5-8fda-a5e5090649e6.png">

I am going to close this issue for now.... feel free to reopen if you see more weirdness.
