### ISSUE TITLE
Building Issues: macOS / Observations 

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#389]
Just noting some issues: when directly building (from just pure checkout)

Script to build platform must be called from root directory else fails: 
```
./scripts/osx/buildPG.sh
```
Can't just CD to ./scripts/osx/ and ./buildPG.sh  

if building from just a pure checkout of projectGenerator rather than within sub of oF 
if ```../openFrameworks``` exists (above it) it will fail rather than continue with that checkout 

Build works and places in:
<img width="533" alt="image" src="https://github.com/openframeworks/projectGenerator/assets/830748/35569c66-2af3-40f1-a205-c48e8994fbab">

Fails to update/build projects due to: (maybe new bug?) 
/Users/one/SOURCE/openFrameworksmacOS/projectGenerator.app/Contents/Resources/app/app/projectGenerator

```
Command failed: /Users/~/SOURCE/openFrameworksmacOS/projectGenerator.app/Contents/Resources/app/app/projectGenerator -v -o"/Users/~/SOURCE/openFrameworksmacOS" -a"ofxTexturePacker" -p"osx"  -t"" "/Users/~/SOURCE/openFrameworksmacOS/addons/ofxTexturePacker"
/bin/sh: /Users/~/SOURCE/openFrameworksmacOS/projectGenerator.app/Contents/Resources/app/app/projectGenerator: No such file or directory

````

Some feedback: 
Can we call the final apps named to their type:

projectGeneratormacOS.app
projectGeneratoriOS.app

**Comment by danoli3** [comment]
Is there a readme or step guide to build outside of ci?

Main issue is GitHub checkouts of the repo (openFrameworks) do not
currently have an easy way to download or build the project generator. This
leads to the user having to download the full latest or nightly build of
the whole repo just to get the latest project generator… I find this to be
quite an issue overtime mostly dealing with the core git repo.

Can we make this flow of the projectGenerator clear:
- to compile it locally
- to just download the binary for the target platform via script from the
GitHub repo (oF main)
- simple readme in the projectGenerator repo on steps (it might be clear to
those on it but wildly confusing, even for me)

**Comment by ofTheo** [comment]
@danoli3 - you are totally right, there is very little documentation on how to get it setup and built. 
made a ReadMe.md for the project. 

https://github.com/openframeworks/projectGenerator/blob/master/ReadMe.md
