### ISSUE TITLE
cannot add new addons during update

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/projectGenerator#39]
if you select a project file to update, and add an addon to the project, it is not added to the project file or the addons.make file.

**Comment by ofZach** [comment]
hmm, I'm not seeing this behavior.  can you post screenshots or a console log of the update operation?

create a new project 

<img width="456" alt="screen shot 2015-09-12 at 4 32 40 am" src="https://cloud.githubusercontent.com/assets/142897/9830737/991e4e30-5907-11e5-8d76-e05b441aaed1.png">

import it, add an addon

<img width="460" alt="screen shot 2015-09-12 at 4 33 41 am" src="https://cloud.githubusercontent.com/assets/142897/9830738/9e9781c4-5907-11e5-9fd3-3071a3d40769.png">

console shows it added 

<img width="469" alt="screen shot 2015-09-12 at 4 33 49 am" src="https://cloud.githubusercontent.com/assets/142897/9830740/abd0701c-5907-11e5-9224-e928aad1ac25.png">

see it addons.make

<img width="321" alt="screen shot 2015-09-12 at 4 34 05 am" src="https://cloud.githubusercontent.com/assets/142897/9830741/af467cdc-5907-11e5-8ae2-f8d5887493c0.png">

see it in sidebar

<img width="130" alt="screen shot 2015-09-12 at 4 34 10 am" src="https://cloud.githubusercontent.com/assets/142897/9830742/b44fc382-5907-11e5-99f1-f1aa1a0662d6.png">

**Comment by ofZach** [comment]
ps: I have noticed wonky behavior on paths with spaces (basically it's failing to do anything right since it doesn't get the right path to the project) 
https://github.com/openframeworks/projectGenerator/issues/41

**Comment by kylemcdonald** [comment]
sorry, this one might have been premature. i was able to do it twice earlier with a project that had ofxCv and i was trying to add ofxOpenCv to it, and nothing was happening. i might have just been in a weird state, i've been able to add other addons to projects since reporting this. closing for now until i can describe more specific steps to recreate.
