### ISSUE TITLE
Again, local addons not working! 

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/projectGenerator#391]
Hi Guys,
please let me rant for a sec.
I've been part of this community for quite long, so please let me indulge a bit.

Local addons are not working, again in PG. While I have not been developing it, and I really appreciate the effort of whom are, I am not understanding why there are changes being made for stuff that used to work and now does not. I am a of the philosophy of "don't fix if it is not broken" to which I would add "yet if you do make super sure that it will not break anything". 

I am sure there are many thing to improve and feature to add but, considering the limited resources I would rather not spend these on "fixing" stuff that does not need to.

So, the local addons is a feature that I use a lot, and it is a bit annoying not being able to use with the newesst PG, thus with the recent nightly builds.

At some point there was a move from using strings for paths to use fs::path instead, where it is I think things began to get broken. 

I find that the following change, from

https://github.com/openframeworks/projectGenerator/blob/272811670ddc0f89450a3727a3ac2e619daf5f49/ofxProjectGenerator/src/projects/baseProject.cpp#L264-L300

to

https://github.com/openframeworks/projectGenerator/blob/48dce6a9cdfb871f4ae1ed3985695dcd4646f057/commandLine/src/projects/baseProject.cpp#L292-L297

did a lot of harm. 

At least to me it is quite clear that assuming that local addons are ONLY those specified by an absolute path in the addons.make file is wrong. 

I will try to fix this but it is a a bit annoying to fix something that was fine and did not need any fixing in the first place.

Last but not least.
Please dont get me wrong. I really, really appreciate your hard work and I love that you are guys are actively developing this, but it is a bit heart breaking when you see something that works nicely to stop doing so. 

Take care!

**Comment by dimitre** [comment]
Hello @roymacdonald thanks for the message, I'll be fixing this and other issues soon.
it is a painfull process and PG is a really complex project but we are almost there.

**Comment by roymacdonald** [comment]
Hi @dimitre 
I've noticed you are one of those working hard on this. Thanks, I really appreciate it.

I am looking at it as well but you might have a better idea on how to fix it. I'll work on it over the weekend, that way you can get a bit off your shoulders. :)

best

**Comment by dimitre** [comment]
Hello @roymacdonald I've made some changes today and it is working according to my tests. 
Please share your addons.make file so I can understand if you are using a different situation from the tests I'm using.
Gracias

**Comment by dimitre** [comment]
@roymacdonald can you please test again to see if the issue is still relevant? thanks
