### ISSUE TITLE
Project Generator Frontend - Windows - Only the commandline 

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#395]
The latest download from projectGenerator doesn't bundle the electron app, only the commandLine app

Edit: Nightly release packages PG OK, this is exclusive to packages generated here (I thought nightly was pulling from this release)

**Comment by moebiussurfing** [comment]
Hello @dimitre , 
I have just seen the forum post asking for testing.
I have been able to open the project with VS 2022.
also i am stuck on the command line getting several errors...
I am on a new Windows 11...

**Comment by moebiussurfing** [comment]
I tried the release binary also here but it's just closing fast when double click.

**Comment by dimitre** [comment]
Please report the errors. I think PG is bundled correctly in OF nightly, just not working if you download directly from this repo

**Comment by moebiussurfing** [comment]
btw this one is working: https://github.com/openframeworks/openFrameworks/releases/tag/nightly

**Comment by dimitre** [comment]
@moebiussurfing open one issue describing what is happening, or steps to reproduce
