### ISSUE TITLE
Can't generate project on Linux

### ISSUE THREAD

**Issue by jildertviet** [openframeworks/projectGenerator#398]
Conversation started [on the forum](https://forum.openframeworks.cc/t/projectgenerator-testing-help-needed/42286/2).

So I'm on Linux Mint 21.2 and testing the PG. 
I'm on the branch [pgup](https://github.com/dimitre/openFrameworks/tree/pgup) by @dimitre, 90f3b62.
So I'm using:
`[notice ] PG v.16` (Not v.17, as mentioned on the forum... I don't know why). 
Anyway, the problem I mentioned persists, this is the error message:
/home/jildert/testOFPG/pgup/openFrameworks/apps/projectGenerator/commandLine/bin/projectGenerator  -o"/home/jildert/testOFPG/pgup/openFrameworks" -a"ofxGui" -p"osx"  -t"" "/home/jildert/testOFPG/pgup/openFrameworks/apps/myApps/mySketch"
[notice ] PG v.16
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: No such file or directory [/home/jildert/testOFPG/pgup/openFrameworks/apps/myApps/mySketch]
Aborted (core dumped)
```
Another thing is that the PG defaults to OSX, I can only change this when I enable Advanced Settings.
After that the problem is still there.

**Comment by jildertviet** [comment]
Ah, I got it:
The directory apps/myApps doesn't exist (only in the builds then I guess).
After creating the directory it works...

**Comment by dimitre** [comment]
Great! I'll implement a proper error message in this case.

**Comment by dimitre** [comment]
Other than handling this error, should we create the folder myApps in git? 
what is your opinion @ofTheo ?

**Comment by dimitre** [comment]
Ok PR Merged!

**Comment by jildertviet** [comment]
This gives a nice human readable error in the CLI. 

But it isn't visible in the GUI. 
In the GUI this block is executed: https://github.com/openframeworks/projectGenerator/blob/c1d23a0b48e223c778c6f4f4c20048ea6dde6b57/frontend/index.js#L928-L938
Which prints `error.message`, which seems empty.
If I change it to `stdout` it shows me the useful message. 

This isn't a fix but a clue, I guess. 
So:
- Should it execute this block, or the one below (`if(wasError === true)`)?
- According to this comment, it should be the `wasError` block.https://github.com/openframeworks/projectGenerator/blob/c1d23a0b48e223c778c6f4f4c20048ea6dde6b57/frontend/index.js#L915

**Comment by ofTheo** [comment]
yeah I would even be in favor of the PG making the myApps folder if it doesn't exist.

**Comment by dimitre** [comment]
@jildertviet  I'll be closing this one, feel free to open a separate one on frontend if needed.

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/projectGenerator/pull/399
