### ISSUE TITLE
ProjectGenerator nightly release - VS is command line only

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#401]
I've noticed the nightly releases in this repo are generating a PG for windows without Electron.
I suppose maybe it is something wrong in the actions file
it seems build-vs.yml to point to a different place like commandLine this:
```
../openFrameworks/apps/projectGenerator/commandLine/bin/projectGenerator-vs.zip
```
in macOS we can see it pointing to another folder.
```
files: ../openFrameworks/apps/projectGenerator/projectGenerator-osx/projectGenerator-osx.zip ../openFrameworks/apps/projectGenerator/projectGenerator-ios/projectGenerator-ios.zip
```

fixing this issue will help testing with the latest changes.

**Comment by ofTheo** [comment]
yes, this is intended but definitely not ideal. 
the packaging is happening in the main OF/OF scripts, as that can be done on Linux but the actually command line exe is being built here. 

it would be better though as you mention that the downloads in OF/PG releases can actually be run ( right now they are just assisting with the main packing process but not really designed to be downloaded and use ). 

I'll take a look at this.

**Comment by danoli3** [comment]
Fixed for VS 
- projectGenerator-vs-gui.zip (ui) 

- projectGenerator-vs.zip (command line)
