### ISSUE TITLE
[Xcode] sanitize project name for Bundle Identifier

### ISSUE THREAD

**Issue by artificiel** [openframeworks/projectGenerator#403]
spaces are OK in project names, however not in bundle identifiers:

https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier

the PG should sanitize the bundle identifier (anything not a-z, A-Z, 0-9, "." and "-" should become "-").

it's pretty much what Xcode does if you try to type in funny stuff (but it will honor the value generated "under the carpet" by PG, albeit with a warning)

**Comment by dimitre** [comment]
Agreed. I've seen this once.
It seems to be set inside Project.xcconfig using $(TARGET_NAME) . maybe a XCode internal variable.
how we can properly sanitize this? maybe a regular expression that sets a User-defined variable in project?

**Comment by artificiel** [comment]
yes editing the xcconfig works!

so I'm not limpid on PG structure but probably in `xcodeProject::createProjectFile()` something like:
```c++
std::regex sanitize("[^A-Za-z0-9]");
std::string sanitized_name = std::regex_replace(projectName, sanitize, "-");
findandreplaceInTexfile(projectDir / "Project.xcconfig", "cc.openFrameworks.$(TARGET_NAME)", "cc.openFrameworks."s+sanitized_name);
```

regex tested here https://godbolt.org/z/ToW9d66Mb

maybe the sanitized name could also be useful elsewhere? command-line executables' names, for instance? (although in that context perhaps the underline should be preferred to the dash). also the .html generated for emscripten should not have spaces/funny chars (or urlencode them?) -- but that outside PG scope though)

**Comment by dimitre** [comment]
@artificiel I've just stumbled in an old XCode project here (no OF)  that uses
```
${PRODUCT_NAME:rfc1034identifier}
```
Maybe this can be the solution

**Comment by artificiel** [comment]
Indeed — seems that does the trick!
