### ISSUE TITLE
Xcode CFBundleVersion and CFBundleShortVersionString are not equivalent

### ISSUE THREAD

**Issue by danomatika** [openframeworks/projectGenerator#429]
I've updated to oF 0.12 and notice the openFrameworks-Info.plist sets both CFBundleVersion and CFBundleShortVersionString to `VERSION`. These are *not* equivalent as CFBundleVersion is the build identifier used when uploading to App Store Connect and needs to be different every time you upload a new build for review. CFBundleShortVersionString is what the user will see as the version in Get Info, in Quick Look, etc.

In the Xcode Info.plist interface:
* Version -> CFBundleShortVersionString -> `MARKETING_VERSION` variable
* Build -> CFBundleVersion -> `CURRENT_PROJECT_VERSION` variable

I note the difference as on iOS I typically set the Version to the main version ala "1.2.0" and the Build to a simple number "1" for submitting to Apple. If I need to do another submission, either for TestFlight or because a build was rejected, I increment the Build number without having to change the actual version.

Reference: https://stackoverflow.com/a/31921249

I recommend the following:

* change CFBundleBundleShortVersionString to `MARKETING_VERSION` in https://github.com/openframeworks/projectGenerator/blob/master/commandLine/openFrameworks-Info.plist#L22
* note this difference between `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION` in Project.xcconfig

**Comment by danomatika** [comment]
Oops. The Build setting in the UI uses the `CURRENT_PROJECT_VERAION` variable not `VERSION`. I would propose to use`VERSION` to set the `MARKETING_VERSION` if it's found as people may be using it now. This would update what's shown in the Xcode UI and what gets built into the app Info.plist.

**Comment by ofTheo** [comment]
Yes - this should be fixed. 
Happy to merge a PR with these changes.
