### ISSUE TITLE
update custom icon path info in Project.xcconfig

### ISSUE THREAD

**Issue by danomatika** [openframeworks/projectGenerator#430]
The info on setting a custom icon path is out of date in Project.xcconfig: https://github.com/openframeworks/projectGenerator/blob/master/commandLine/Project.xcconfig#L29

I believe it should be:
~~~
//IF YOU WANT AN APP TO HAVE A CUSTOM ICON - PUT THEM IN YOUR DATA FOLDER AND CHANGE ICON_FILE_PATH to:
//ICON_FILE = bin/data/$(ICON_NAME)
~~~

This works fine on a project that used to set a custom icon using the original ICON_FILE_PATH variable.

**Comment by dimitre** [comment]
Maybe we should remove ICON_FILE_PATH variable entirely?

**Comment by dimitre** [comment]
You can create a file named App.xcconfig, it is an optional include, so settings like icon survive projectGenerator rewrites.
it is useful for app version / icon and other configurations
```xcconfig
//CLANG_CXX_LANGUAGE_STANDARD = c++20
//MACOSX_DEPLOYMENT_TARGET = 12.0

PRODUCT_BUNDLE_IDENTIFIER = org.dmtr.xp
VERSION = 0.0.7

ICON_NAME = xp.icns
ICON_FILE = $(ICON_NAME)

CODE_SIGN_IDENTITY = -;
CODE_SIGN_STYLE = Automatic;

//OF_NO_FMOD = 1
//OF_CORE_LIBS = $(LIB_GLEW) $(LIB_PUGIXML)
//OF_CORE_HEADERS = $(HEADER_OF) $(HEADER_GLEW) $(HEADER_TESS2) $(HEADER_GLFW) $(HEADER_UTF8) $(HEADER_JSON) $(HEADER_GLM) $(HEADER_PUGIXML)
//OF_CORE_FRAMEWORKS = -framework Accelerate -framework Cocoa -framework CoreFoundation -framework CoreServices -framework CoreVideo -framework IOKit -framework OpenGL -framework QuartzCore -framework Security

```

**Comment by danomatika** [comment]
Yes, I do this now, however my point is that the reference in the comment is wrong and `ICON_FILE_PATH` does not appear to be used anymore, so this note should be updated.

**Comment by dimitre** [comment]
Agreed! lets remove it. I was just confused because ```ICON_FILE_PATH``` is mentioned in your suggestion

**Comment by danomatika** [comment]
Also, this is important since the change to oF 0.12 broke the icon on projects I originally set up with the oF 0.10 ICON_FILE_PATH. I think people should at least get a hint on how to fix it...

**Comment by dimitre** [comment]
how about this?
```
//IF YOU WANT AN APP TO HAVE A CUSTOM ICON EDIT ICON_FILE VARIABLE:
//ICON_FILE = bin/data/custom.icns
```

**Comment by danomatika** [comment]
I think it is also important to note should match how the default `ICON_FILE` is set and support both debug and release iconsets: 
~~~
ICON_FILE = bin/data/$(ICON_NAME)
~~~

For instance, in my old Project.xcconfig used with oF 0.11:
~~~
//ICONS - NEW IN 0072
ICON_NAME_DEBUG = icon-debug.icns
ICON_NAME_RELEASE = icon.icns
//ICON_FILE_PATH = $(OF_PATH)/libs/openFrameworksCompiled/project/osx/
ICON_FILE_PATH = bin/data/
~~~

The equivalent overridde in App.xcconfig for oF 0.12 is now:
~~~
// icon
ICON_NAME = icon.icns
ICON_NAME[config=Debug] = icon-debug.icns
ICON_FILE = bin/data/$(ICON_NAME)
~~~

I think a full note about how to transition from the old way to the new way would be helpful, ala:
~~~
// to reenable custom icon loading using ICON_FILE_PATH as used in oF 0.7.2 - 0.11:
// ICON_NAME = icon.icns
// ICON_NAME[config=Debug] = icon-debug.icns
// ICON_FILE = bin/data/$(ICON_NAME)
// if you use a custom openFrameworks.plist, set CFBundleIconFile to ICON_FILE
~~~

**Comment by danomatika** [comment]
That whole section could be overhauled a bit. For example:
~~~
// default oF app icon
ICON_NAME = of.icns
ICON_NAME[config=Debug] = of_debug.icns
ICON_FILE = $(OF_PATH)/libs/openFrameworksCompiled/project/osx/$(ICON_NAME)

// custom icon
//ICON_NAME = MyApp.icns
//ICON_FILE = $(ICON_NAME)
// to reenable custom icon loading using ICON_FILE_PATH as used in oF 0.7.2 - 0.11:
//ICON_NAME = icon.icns
//ICON_NAME[config=Debug] = icon-debug.icns
//ICON_FILE = bin/data/$(ICON_NAME)
// if you use a custom openFrameworks.plist, set CFBundleIconFile to ICON_FILE
~~~

**Comment by dimitre** [comment]
Great! +1 for this change. it is much better without all caps.
@ofTheo any opinion on this?

**Comment by ofTheo** [comment]
@dimitre @danomatika - this all looks great! 
Happy for these changes as long as CI still passes :D
