### ISSUE TITLE
question / bug?: blue arrow button

### ISSUE THREAD

**Issue by artificiel** [openframeworks/projectGenerator#436]
when a project is created/update, a blue arrow icon appears above the name:

![image](https://github.com/openframeworks/projectGenerator/assets/2172370/3c6f068f-b976-430e-aa65-a4b6b888b86f)

it is an appealing icon, however clicking on it does nothing (macOS 14.1, PG 0.1.0 / 2023 08 13).

what is the function of the button (would expect "open project directory") but maybe it's something else?

**Comment by ofTheo** [comment]
closed by #437
