### ISSUE TITLE
Funky paths for local addons libs

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/projectGenerator#44]
The "local addons" support looks like it's working well, thank you again for adding that! It looks like for VS at least I'm getting odd folders in the project ("filters" technically). It compiles fine anyway, and dragging the libs folder to local_addons/ofxAddon/libs so it "looks right" also works. I can test this on OSX as well if that's helpful, let me know!

![pg-addon-paths](https://cloud.githubusercontent.com/assets/2334552/10025044/29ef62e6-6128-11e5-86c7-2cff6d1e9cfb.jpg)

**Comment by arturoc** [comment]
just fixed this in the last commit
