### ISSUE TITLE
Problem setting ADDON_CFLAGS in Xcode projects with OF 0.12 release PG

### ISSUE THREAD

**Issue by danomatika** [openframeworks/projectGenerator#440]
I have been updating my addons for OF 0.12 and I am seeing an issue with setting `ADDON_CFLAGS` in Xcode projects for iOS and macOS and I have run into an issue with [ofxPd](https://github.com/danomatika/ofxPd).

The ofxPd [addons_config.mk](https://github.com/danomatika/ofxPd/blob/master/addon_config.mk) sets the following:
~~~
common:
    ADDON_CFLAGS = -DPD -DUSEAPI_DUMMY -DPD_INTERNAL -DHAVE_UNISTD_H -DHAVE_ALLOCA_H -DLIBPD_EXTRA
osx:
    ADDON_CFLAGS += -DHAVE_LIBDL -DHAVE_MACHINE_ENDIAN_H -D_DARWIN_C_SOURCE
ios:
    ADDON_CFLAGS += -fcommon -DHAVE_MACHINE_ENDIAN_H -D_DARWIN_C_SOURCE
~~~

After generating the Xcode project, only the last flag is set within the project's **Other C Flags**:
![Screenshot 2023-11-16 at 11 33 48 PM](https://github.com/openframeworks/projectGenerator/assets/480637/1a99e25b-046e-45cd-b9d8-079cb2c7559a)

I tried separating the flags into single lines using `ADDON_CFLAGS +=` but this does not change the behavior.

This problem basically breaks (re)generating Xcode projects which use ofxPd. For now, I have added info to the readme on [manually setting the C flags](https://github.com/danomatika/ofxPd/tree/master#of-012-and-xcode-exth-file-not-found).

**Comment by danomatika** [comment]
Should I have opened this on the main openFrameworks repo? I am using the basic GUI projectGenerator included with the OF 0.12 release.

**Comment by dimitre** [comment]
No, this repo is best for this issue. I'll be investigating this

**Comment by danomatika** [comment]
Thanks. Nice that it was an easy fix.

**Comment by dimitre** [comment]
Thanks for reporting. I'll link a note on 0.12.1 release to remember you of changing readme
