### ISSUE TITLE
missing src directory in vscode template

### ISSUE THREAD

**Issue by icq4ever** [openframeworks/projectGenerator#444]
update projectGenerator and run but there's an error

```
icq4ever@tp25-linux [13:06:45] [~/oF/apps/test] [master *]
-> % projectGenerator tt
[notice ] PG v.28

[notice ] -----------------------------------------------
[notice ] target platform is: linux64
[notice ] setting OF path to: "../../.."
[notice ] from PG_OF_PATH environment variable
[notice ] project path is: "/home/icq4ever/oF/apps/test/tt"
[notice ] setting up new project "/home/icq4ever/oF/apps/test/tt"
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot copy: No such file or directory [../../../scripts/templates/vscode/src] [/home/icq4ever/oF/apps/test/tt/src]
[1]    15166 IOT instruction (core dumped)  projectGenerator tt
```

in `_OF/scripts/templates/vscode`, there is no `src` directory and files. 
my repo is wrong? oF is master from the repo.

**Comment by icq4ever** [comment]
i just copied `src` and `bin` directory from `scrips/templates/linux64`, which is my platform. and works. 
i don't know why it's template `vscode` even if i didn't put any target. is this intended ?

**Comment by dimitre** [comment]
Thanks for reporting. 
vscode is intended as default for linux now
I can make a PR to add the missing folders

**Comment by dimitre** [comment]
https://github.com/openframeworks/openFrameworks/pull/7818

**Comment by icq4ever** [comment]
thanks !
