### ISSUE TITLE
PG massive with new Electron macOS 300+mb

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#446]
- Check compiler flags
- Make sure release mode
- disable symbols 

Targets:
- macOS arm64 / x86_64 

Need to get this down

**Comment by danoli3** [comment]
```
otool -v -s __LLVM __bundle "projectGenerator.app/contents/frameworks/Electron Framework.framework/Electron Framework" 
```

returns 
projectGenerator.app/contents/frameworks/Electron Framework.framework/Electron Framework (architecture x86_64):
projectGenerator.app/contents/frameworks/Electron Framework.framework/Electron Framework (architecture arm64):

BITCODE is embedded in the Electron Framework.... yeah remove that

**Comment by danoli3** [comment]
Okay this fixed via: https://github.com/openframeworks/projectGenerator/pull/450

**Comment by ofTheo** [comment]
cool!! 
just to check, is it still packaging a universal PG?  

x86_64 PG runs super slow on arm64 for some reason.

**Comment by danoli3** [comment]
It's easily configurable, I've made it universal again now

**Comment by danoli3** [comment]
Yeah had some issues but your fix idea solved it! yay
