### ISSUE TITLE
Feature request: open in xcode or any other ide button

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#46]
I would like to be able to open a successfully generated project in xcode or any other ide via the projectGenerator.
There could be an open button next to the log window's close button.
Maybe the following commands are useful:

osx: ``òpen $DESTINATION_PATH```

linux: ```xdg-open $DESTINATION_PATH```

**Comment by kylemcdonald** [comment]
i like your command line solution! some other thoughts on this issue at #40

**Comment by Daandelange** [comment]
I made this XCode feature in this commit, and it works great!
It should not be hard to add the linux method.
https://github.com/Daandelange/projectGenerator/commit/a17476e5a81f377cf98094cdc7eb622a7dd41d3b

**Comment by ofZach** [comment]
I suggest we do this in the success modal for now, and then later versions drop the modal as @kylemcdonald suggests.  Right now, doing it w/ the update / generate buttons feels a little strange, the UI is kind of popping around, and I feel more comfortable adding it the modal then working it into the main ui....

**Comment by ofZach** [comment]
I've added a PR putting this in the success modal (using the code that @Daandelange wrote) for now: 

https://github.com/openframeworks/projectGenerator/pull/73

I think after 0.9 we can revisit the overall UI and improve....

**Comment by ofZach** [comment]
this has been added, thanks for the suggestion!   please test !
