### ISSUE TITLE
Nightly OF/OF broken

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#465]
https://github.com/openframeworks/openFrameworks/actions/runs/7258030658/job/19772724556

cc @danoli3 @dimitre 

I think its tied to these changes:
https://github.com/openframeworks/projectGenerator/commit/63975db3a4987cf8110b615f1cfd43f11de815e8#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655R1-R75

```
Creating project files for linux64
[ error ] VSCodeProject: JSON parse error at byte1
Creating projectGenerator
npm ERR! Missing script: "build:linux64"
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     npm run dist:linux64 # run the "dist:linux64" package script
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

**Comment by dimitre** [comment]
oww, I've submitted a PR just to investigate if the template file is in the right place.
https://github.com/openframeworks/projectGenerator/pull/467
ready to merge and manually run actions when it pass tests

**Comment by dimitre** [comment]
PR merged and manual nightly started

**Comment by ofTheo** [comment]
I think the issue is we're missing: 
https://github.com/openframeworks/projectGenerator/commit/63975db3a4987cf8110b615f1cfd43f11de815e8#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655L23

I think adding a new entry below this one:
https://github.com/openframeworks/projectGenerator/commit/63975db3a4987cf8110b615f1cfd43f11de815e8#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655R51-R57

with:

```
    "linux64": {
       "icon": "static/icon",
       "target": {
         "target": "tar.gz",
         "arch": ["x64"]
       }
     },
```

might be the fix?

**Comment by dimitre** [comment]
I hope so! no idea of what happened 🪱

**Comment by dimitre** [comment]
Ok, I've just tested manual nightly again, and it now shows a missing path, 
I'm not sure why projectGenerator is trying to find this one
It seems the templates folder path is wrong. any ideas @danoli3 ?
```
examples/templates/emptyExample/emptyExample.code-workspace
```

**Comment by ofTheo** [comment]
okay - I just tried locally and adding this back fixes the missing build:linux64 

```
    "build:linux64": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=25.3.0 --platform=linux --arch=x64"
```

**Comment by ofTheo** [comment]
@dimitre going to run the nightly manually again and then look at the vscode template issue

**Comment by ofTheo** [comment]
@dimitre so currently the nightly build is using the command line PG to add the template flag for vscode, this way it can make both VS code projects and Xcode projects for macOS. 

Not sure if that is the best way to do it or we should be using the new approach you added. 
Is it possible to have PG generate VS Code and Xcode both via the platform/project arg ?

**Comment by ofTheo** [comment]
hmm so the error has been there even in working nightly builds so it might just be an error that is unrelated to this issue:

<img width="985" alt="image" src="https://github.com/openframeworks/projectGenerator/assets/144000/148ab7ec-bbbc-4f21-8c87-650233b7d527">

**Comment by ofTheo** [comment]
okay its working again

**Comment by dimitre** [comment]
Glad you found and fixed really quick. 
it was introduced a week ago in that /src /bin PR. 
Hoping nobody lost code with this one. Should I add a pinned issue to notify?
