### ISSUE TITLE
Latest OF nightly has blank examples 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#466]
Not sure which commit caused this, but all examples in the last nightly build on OF/OF are blank - just have the emptyExample ofApp.cpp and ofApp.h. 

Looked at both linux and macOS zips from: https://github.com/openframeworks/openFrameworks/releases/nightly 

<img width="1400" alt="image" src="https://github.com/openframeworks/projectGenerator/assets/144000/d79c8b43-65b1-486b-a75b-2fcc50fa61b4">

**Comment by dimitre** [comment]
I'm now investigating this one 
I can't reproduce locally with projectGenerator commandLine (recursively updating)
I'll be taking a better look

**Comment by ofTheo** [comment]
Just tried using the PG gui and updating a project which has a src/ folder and it replaces it with the code from `scripts/templates/osx/src`

this was the PG Gui output ( I am guessing the `setting up new project` line is the culprit ):

```
[notice ] PG v.33

[notice ] -----------------------------------------------
[notice ] target platform is: osx
[notice ] setting OF path to: "../../.."
[notice ] from -o option
[notice ] project path is: "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"
[notice ] setting up new project "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"

[notice ] updating project "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"
[notice ] saving addons.make
[notice ] project updated! 
[notice ] -----------------------------------------------

[notice ] -----------------------------------------------
[notice ] target platform is: vscode
[notice ] setting OF path to: "../../.."
[notice ] from -o option
[notice ] project path is: "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"
[notice ] setting up new project "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"

[notice ] updating project "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"
[notice ] saving addons.make
[notice ] project updated! 
[notice ] -----------------------------------------------


1 project created [notice ] in 0.0270823 seconds





(command used: /Users/theo/Downloads/of_v20231221_osx_release/projectGenerator/projectGenerator.app/Contents/Resources/app/app/projectGenerator  -o"/Users/theo/Downloads/of_v20231221_osx_release" -a" " -p"osx,vscode"  -t"" "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample")
```

**Comment by ofTheo** [comment]
I suspect its something here in baseProject.cpp the testing for "src/" 
https://github.com/openframeworks/projectGenerator/commit/4985bdbd91003d649c150b3bf1e1b6ed0daafde1

**Comment by ofTheo** [comment]
Okay just rebuilt the PG with some debugging info. 

If I just do Xcode it works fine. 
But if I do Xcode and VSCode or just VSCode the files get replaced. 

In both cases I only see: 

```
[notice ] updating project "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample"
[notice ] DEBUG 1 - src folder path is "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample/src"
[notice ] DEBUG 2 - src folder path should be? "/Users/theo/Downloads/of_v20231221_osx_release/examples/3d/3DPrimitivesExample/src"
```

And I don't see these lines: https://github.com/openframeworks/projectGenerator/blob/4985bdbd91003d649c150b3bf1e1b6ed0daafde1/commandLine/src/projects/baseProject.cpp#L162-L163

So it must be something in VSCodeProject

**Comment by ofTheo** [comment]
So I think this line is the issue: 
https://github.com/openframeworks/projectGenerator/blob/master/commandLine/src/projects/VSCodeProject.cpp#L76

The code in BaseProject is already handling the copying of bin/ and src/ 

So `VSCodeProject::createProjectFile()` shouldn't be copying those files - but currently it is copying the contents of the whole directory including bin/ and src/ 

So I think we would maybe want to copy all non directories + `.vscode` directory or find a way to copy everything but bin and src

**Comment by ofTheo** [comment]
going to do a quick fix for this as there is a serious danger of deleting people's source code.

**Comment by dimitre** [comment]
Great @ofTheo thanks for the investigation and the fix

**Comment by ofTheo** [comment]
Hoping this fixes it! 🤞
https://github.com/openframeworks/projectGenerator/commit/536b1b389ee1b899c5378c89e6882221aad7f069

**Comment by ofTheo** [comment]
Okay my last changes fixed people's projects getting overwritten if platform is vscode, but if a template is specified with a `-tvscode` ( which OF/OF nightly is using ) this code is getting executed:

https://github.com/openframeworks/projectGenerator/blob/master/commandLine/src/projects/baseProject.cpp#L174-L183

with recursiveTemplateCopy being called - which always overwrites the src/ and bin/ from `templates/vscode/` into the project folder. 

So this whole issue comes from this PR where src/ and bin/ were added to `vscode` when it was changed from a template to a project.  https://github.com/openframeworks/openFrameworks/pull/7818 

Before templates did not contain src or bin as they were meant to be used alongside a project, but vscode is both a template and a project so adding the src/ and bin/ created the issue. 

A good fix will be to exclude bin/ and src/ from `recursiveTemplateCopy` but we should also switch to using -pvscode for OF/OF
