### ISSUE TITLE
Windows binary from nightly builds do not open

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/projectGenerator#469]
Hi, I downloaded and copied the PG.exe from
https://github.com/openframeworks/openFrameworks/releases/download/nightly/of_v20231222_vs_release.zip

**Comment by moebiussurfing** [comment]
BTW
Is common problem with other binaries... so it could be something on my system...

**Comment by dimitre** [comment]
Hey @moebiussurfing I'm pretty happy we can now download projectGenerator vs-gui here
https://github.com/openframeworks/projectGenerator/releases
I've used yesterday with sucess in windows.
Thank you @danoli3

**Comment by ofTheo** [comment]
@moebiussurfing - could you share the error message or is it completely silent?
It might be system protection kicking in - sometimes you can click More Info and - then Run Anyway 

Do you see something like this?

![image](https://github.com/openframeworks/projectGenerator/assets/144000/e6a87d00-093b-4200-a5df-371e9e8928a9)

**Comment by moebiussurfing** [comment]
> Hey @moebiussurfing I'm pretty happy we can now download projectGenerator vs-gui here [openframeworks/projectGenerator/releases](https://github.com/openframeworks/projectGenerator/releases) I've used yesterday with sucess in windows. Thank you @danoli3

it worked perfect. good to see this new PG link

**Comment by moebiussurfing** [comment]
> @moebiussurfing - could you share the error message or is it completely silent? It might be system protection kicking in - sometimes you can click More Info and - then Run Anyway
> 
> Do you see something like this?
> 
> ![image](https://private-user-images.githubusercontent.com/144000/292594440-e6a87d00-093b-4200-a5df-371e9e8928a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyODgzMjksIm5iZiI6MTcwMzI4ODAyOSwicGF0aCI6Ii8xNDQwMDAvMjkyNTk0NDQwLWU2YTg3ZDAwLTA5M2ItNDIwMC1hNWRmLTM3MWU5ZTg5MjhhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQyMzMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGEyNjhhNjhlZmM0MGE2NzJhZDE1YmM2OTM5MWE3MTQxNDUzNmRmOTE5NTg4MDIzYjE4ZjNjNzkzOTJiNGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LuiTjgZ2QdBNbyS9_IrMNmuWESXpBwBB4hBB2BPdiOA)

no, it was showing half a second turning the mouse arrow and nothing more. even opening as admin

**Comment by dimitre** [comment]
Nice! @moebiussurfing let us know if the OF nightly projectGenerator worked?
if the nightly isn't working we should left the issue opened

**Comment by moebiussurfing** [comment]
i'll try someday after rebooting the system

**Comment by ofTheo** [comment]
@dimitre does the current nightly OF/OF package from: https://github.com/openframeworks/openFrameworks/releases/tag/nightly work for you on Windows?

**Comment by dimitre** [comment]
ok I've just tested now downloading OF nightly VS and uncompressing projectGenerator from there, 
it triggers windows defender but opens correctly once you set to ignore

**Comment by moebiussurfing** [comment]
do not worked even after reboot.
but fixed just setting the settings/account/UAC mode to default.

**Comment by moebiussurfing** [comment]
I'm not sure how randomly is behaving but that's what I can say.

BTW
I have also seen this tweak that helped me to fix an installer:
https://www.elevenforum.com/t/this-file-came-from-another-computer-and-might-be-blocked.2011/

**Comment by danoli3** [comment]
Yeah we really need to look at getting a signed key, a good option is to apply to SignPath Foundation 
https://signpath.org

Otherwise signing keys can be subscription based, yearly and minimum $30-100 usd 

@paulsavoie of Sign Path, would sign path be willing to help our open source openFrameworks sign our projectGenerator used for Developer Tools 
Please contact @ofTheo
