### ISSUE TITLE
no .gitignore is created when using gitignore template (iOS, nightly version)

### ISSUE THREAD

**Issue by lmtanco** [openframeworks/projectGenerator#477]
Hi there! 

I am using the version of projectGenerator in `of_v20240109_ios_release` nightly build. 

**When creating a project with the git ignore template no `.gitignore` is generated.** 

I am not sure how this works but this might be related to the fact that there is no `.gitignore` bundled in `of_v20240109_ios_release/scripts/templates/gitignore`, when there is one in [GitHub](https://github.com/openframeworks/openFrameworks/tree/master/scripts/templates/gitignore)

![image](https://github.com/openframeworks/projectGenerator/assets/1093084/6e24138a-8cca-4e3c-8f80-4700adaf85e1)

Many thanks!

Luis.

**Comment by danoli3** [comment]
@ofTheo must be something in nightlight not packaging .gitignore in the zip releases

**Comment by danoli3** [comment]
Still occurring ! Forgot about this

**Comment by lmtanco** [comment]
Thank you! :)
