### ISSUE TITLE
issue compiling in windows

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#480]
I'm trying to compile projectGenerator (command line only) on windows, using both msbuild from vs2019 and from vs2022 with no success.
I've tried to install libs using ```download_latest_libs.sh``` and now I have some issues related to what seems to be a duplicate libpng. one already defined in FreeImage.
Do you know what is needed to compile @danoli3  ?

**Comment by ofTheo** [comment]
@dimitre - I would check the Windows Github Actions steps as they might provide a clue: 

eg: setup for VS:
https://github.com/openframeworks/projectGenerator/blob/master/.github/workflows/build-vs.yml#L59 

build for VS:
https://github.com/openframeworks/projectGenerator/blob/master/.github/workflows/build-vs.yml#L66

**Comment by danoli3** [comment]
Hmmm let me see if something wasn’t uploaded properly on PG vs settings

If you are getting for double included lib that should be a warning at
worst i think maybe need to add a flag for msbuild


On a side note:
I am currently looking into FreeImage libpng anyways as it’s having some
issues at the moment at 3.19.0

I’ll be out of hospital in a few hours I’ll jump on it regardless

**Comment by danoli3** [comment]
Oh make sure your openFrameworks is on master latest that is being used !

**Comment by danoli3** [comment]
@dimitre should be fixed I could see why maybe it wasn't working due to paths // (although that was the same before so weird) 
Let me know

**Comment by dimitre** [comment]
@danoli3 yes it is back working again. The default now is vs2022?
ah should we have two vs templates for OF projects? vs2019 / vs2022? 
I think it is useful

**Comment by danoli3** [comment]
I agree useful just requires all the libraries built for v142 as well. Possible.

I'm actually running some bots locally and testing CLANG for VS2022 though and omfg ITS SO FASTT!!!! 
But anyways happy to quickly edit up a v142 2019 template for the moment but ideally we switch to 2022 and its seamless
