### ISSUE TITLE
Fix .Metal shader import type

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#486]
As reported in Live repo @sortofsleepy
https://github.com/sortofsleepy/ofxARKit

<img width="671" alt="Screenshot 2024-03-06 at 5 12 33 pm" src="https://github.com/openframeworks/projectGenerator/assets/830748/e1eeba22-9e73-4ae2-93de-9466023679f5">

> This addon involves use of Apple's Metal framework to handle camera imaging and processing as the raw feed from your phone/tablet's camera comes in unprocessed. In the src files there is a Shader.metal file included which handles turning that unprocessed image into something more recognizeable. There is also Metal code that takes care of translating the resulting Metal textures to OpenGL compatible ones. At the time of this writing, for some reason, projectGenerator does not treat .metal files correctly and labels it as a Data file instead of a Metal file. You will likely have to change it to it's correct designation by using the file inspector in Xcode. projectGenerator also does not automatically add it to the list of compiled sources for a project so you will have to do that as well.

**Comment by dimitre** [comment]
Nice, I think this one should not be hard to address in the up to date PG

**Comment by sortofsleepy** [comment]
Ah, I almost forgot about this. I actually opened an issue many many years ago about this
 #183

**Comment by dimitre** [comment]
I think this one can be closed
I've recently generated the basic example in ofxARKit and it seems the Metal shader is OK.
Can you please verify it @sortofsleepy ? Thanks!
<img width="1147" alt="Screenshot 2024-05-20 at 20 40 20" src="https://github.com/openframeworks/projectGenerator/assets/58289/28c139fc-4d34-4e2f-808d-2fb74ed8e8c6">

**Comment by sortofsleepy** [comment]
> I think this one can be closed I've recently generated the basic example in ofxARKit and it seems the Metal shader is OK. Can you please verify it @sortofsleepy ? Thanks! ..

🎉 @dimitre

Unfortunately I have no Mac or iPhone at the moment so I can't check myself but I'll take your word for it. If the project generator copies  and defines things properly then great! Feel free to close. 

_note that even though the file is now properly defined and copied over, you might still have issues actually running the examples, see the pinned comment under issues inside the project._

**Comment by dimitre** [comment]
Great I'll left it open for now. 
I have an ancient iPhone here from 2016, let's see if I can use it to test later 📱

**Comment by dimitre** [comment]
I've tested here, I'm not sure if it fixes because the addon fails somewhere else
```
/Volumes/tool/ofw/addons/ofxARKit/src/lib/ARSessionSetup.h:72:50 No known class method for selector 'supportsFrameSemantics'
```

**Comment by sortofsleepy** [comment]
hmmm that's a new one for me considering the function "should" exist [according to this](https://developer.apple.com/documentation/arkit/arconfiguration/3089122-supportsframesemantics). I'm assuming you attempted to re-integrate the addon? Did you remember to add the ARKit framework? 

In any case, I would say that that is a separate issue I'll have to somehow try and address at some point(though who can say when that'll be in this job market 😞 ). As long as Metal shaders are recognized correctly and added to the list of compiled sources then I think it's fine to close this issue.

**Comment by dimitre** [comment]
Glad you pointed me to adding ARKit. I've added and the error persists
in fact I'm updating the projectGenerator so ADDON_FRAMEWORKS get added automatically to the folder and build phases

**Comment by dimitre** [comment]
@danoli3 can you please test this one to see if it is working?

**Comment by danoli3** [comment]
@dimitre yep this is working
