### ISSUE TITLE
Xcode projects crashing on load.

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/projectGenerator#488]
I am using 15.2 and OSX 13.6.4 on an intel processor machine.

of_v0.12.0_osx_release cannot run as it links to GLUT.framework and that cannot be codesinged - as far as I can tell - there is no way for me choose how to deal with this so that does not work.

I am trying with the nightly builds, but there seems to be maybe an issue with the project generator when using a lot of my regular addons.

The project generator (I pulled the current master and built it to try to mitigate this issue) makes the projects, everything looks fine but then the projects crash straight away. These addons were working for me some time ago - not exactly sure which commit had everything going.

One example addon I am trying to use is: https://github.com/pierrep/ofxTimeline

Trying the same stuff on windows gives another set of errors (Visual Studio community 2022, Windows 10 - A setup that was working fine), when running release I get:

"Binary was not built with debug information" for code that worked somehwere between the 0.12 release and now.

I am happy to degub this but I am at a loss and have a project delivery rebuild looming in the coming days.

I am taking a stab in the dark that the PG is cuasing the issue. 

Building the same projects for VScode on OSX works fine.

**Comment by dimitre** [comment]
I had a similar issue recently and it was some random files inside src folder
if you want me to test generating your projects here please send me a .zip file. 
and if you don't want to share any source copy some example from OF

**Comment by fred-dev** [comment]
I made fresh projects to test this, so nothing in the src folder. Generating a fresh Xcode project with many of the addons I use seems to run sucessfully but Xcode crashes trying to open the file. The error is thousands of lines long so it is a bit hard to debug further - I dont have much knowledge of the project structure to know where to start looking.

I have attached a zipped project - I just used PG to generate a new project for osx Xcode with the ofxTimeline addon included. 

Generating a VScode project with the same addons works perfectly - I am now coding in there and getting used to it.

Let me know if this opens for you at all or if you have any idea what the issue is.

[timelineTest.zip](https://github.com/openframeworks/projectGenerator/files/15336001/timelineTest.zip)

**Comment by dimitre** [comment]
I've just tested your project and crashed. I've generated again and it worked.
the diffs are mainly the relative path to addons, yours is ../.. and mine is default ../../..

**Comment by dimitre** [comment]
[tt.xcodeproj.zip](https://github.com/openframeworks/projectGenerator/files/15336131/tt.xcodeproj.zip)

**Comment by dimitre** [comment]
ofxTween is missing from addons.make list
my suggestion is you can try removing addons to see if you find which is causing the issue

**Comment by fred-dev** [comment]
Ok, I see it, the xcode PG cannot handle other file types in any of the folders at all. There is a termsofuse.html in a subfolder inside ofxTween https://github.com/arturoc/ofxTween/tree/master/src/Easings I guess this is the cause accross the board. This is not uncommon though, especially if an addon contains a downloaded library that has such TOS or other info files inside.

I have been using these for years and the PG has never had this issue before. Is there a file type filter that has been removed? Any idea of the commit where this change in behaiviour was implemented?

**Comment by dimitre** [comment]
I can address this in near future. my suggestion is you make your fork of ofxTween for now.
projectGenerator for XCode was mostly rewritten a while ago, you have to use 0.11.2 to use the XML based old one.

**Comment by dimitre** [comment]
This is closed in the latest PR. projectGenerator is now on version 35.
Please open a separate issue for VS
