### ISSUE TITLE
after adding the ofxgstreamer there's no filter group

### ISSUE THREAD

**Issue by liquidzym** [openframeworks/projectGenerator#491]
not too sure is it realated with pg or the addons.make file?  there's no filter group folder which is should like ofxgui, instead of all souce code going to src folder 
![QQ截图20240517183213](https://github.com/openframeworks/projectGenerator/assets/51957/5ead90d0-5078-4ff6-9703-41cd0c0bf048)

**Comment by dimitre** [comment]
Thanks for reporting. I'll be adressing this issue soon.

**Comment by dimitre** [comment]
ok it seems ofxGStreamer is adding some files from the core, instead of the addon, I'll be updating to create a folder called "other" so it is more organized now.
It is strange that in your printscreen the files from ofxGui are outside the folder also, did you move them?

**Comment by liquidzym** [comment]
no,i didn't move them, this issue only with with ofxGStreamer addons,it add source file from the core,so you add other addons like ofxgui or whatever is ,all going to outside the folder

**Comment by dimitre** [comment]
here is the PR to organize ofxGStreamer files into "other" folder https://github.com/openframeworks/projectGenerator/pull/494

the issue with ofxGui folder didn't happen here

**Comment by liquidzym** [comment]
thank you so much for the help, the issue gone！

**Comment by dimitre** [comment]
I've recently fixed another issue where some OF Core files were outside of their folders. it is correct now if you pull the latest from openFrameworks repository, and re-generate your projects.
