### ISSUE TITLE
Creating a VS project from OSX leads to folders created with "\" in their name 

### ISSUE THREAD

**Issue by armadillu** [openframeworks/projectGenerator#495]
Creating a basic project from OSX, leads to my newly created project containing directories that look off.

<img width="318" alt="image" src="https://github.com/openframeworks/projectGenerator/assets/167057/e633f1ae-22cd-4461-9ba9-be38c03fd3ff">

**Comment by dimitre** [comment]
this PR fixes the logic of folders creation (will be merged after tests)
https://github.com/openframeworks/projectGenerator/pull/496/

but it will still create a dll folder with some folders inside. 
I'll cc @danoli3 here so we know if this empty folders are important

**Comment by dimitre** [comment]
now merged
https://github.com/openframeworks/projectGenerator/pull/496
