### ISSUE TITLE
ofTargetPlatform OF_TARGET_MACOS missing

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#538]
Hey @danoli3 I think you should probably update constants in OF repo so this can run.

```
./src/utils/Utils.h:27:7: error: use of undeclared identifier 'OF_TARGET_MACOS'; did you mean 'OF_TARGET_IOS'?
    { OF_TARGET_MACOS, "macos" },
      ^~~~~~~~~~~~~~~
      OF_TARGET_IOS
```

**Comment by danoli3** [comment]
Should be since: 786bb2e4eb841767b8129b722344b73422ab3da2

git fetch and pull again

**Comment by danoli3** [comment]
Actually this might break running against older, disabling this

**Comment by dimitre** [comment]
Good, thanks
