### ISSUE TITLE
first run in package location on osx yields can't find oF path what

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#542]
<img width="866" alt="Screenshot 2024-07-11 at 6 55 24 PM" src="https://github.com/openframeworks/projectGenerator/assets/830748/d66bd93b-d82f-4508-9e89-47e9db1afbd6">

how didnt it find it automatically, needs review

**Comment by danoli3** [comment]
I think this is occurring randomly due to projectGenerator living at openFrameworks/projectGenerator.app/Contents/MacOS/projectGenerator 

so its checking code for ../../ or ../../../ is not working. Adding dynamic up folder check

**Comment by ofTheo** [comment]
This is App Translocation which is a security feature of macOS. 
It gives the app a randomized runtime directory until you move it manually in the Finder. 

We've tried a ton of things to break App Translocation but nothing works well. 
I even tried a signed DMG for the whole OF package but it didn't solve it. 

So the above message is normal ( but I should note is designed for people using the whole OF package ), so as soon as you move it into OF_FOLDER/projectGenerator/ the message should go away and it will see the OF path. 

Feel free to close if that's it.

**Comment by danoli3** [comment]
Fixed with auto finder  oF code up folder parents.
ofPath is found by directory level of sub folders: addons / libs / scripts
prior was just sub folder "scripts" ? 

<img width="806" alt="Screenshot 2024-07-12 at 2 31 19 AM" src="https://github.com/openframeworks/projectGenerator/assets/830748/8c71d2f6-6987-4c43-ac85-8b27ec3ffbcd">

**Comment by danoli3** [comment]
@ofTheo yes I noticed now the current_path was / 

```fs::weakly_canonical(fs::current_path());```  = /
```ofFilePath::getAbsolutePathFS(fs::current_path(), false);``  = /

```fs::path startPath = ofFilePath::getCurrentExeDirFS();``` = real path where I then ran from paths upwards to parent folders

**Comment by ofTheo** [comment]
Ah sweet! Nice approach 😁
