### ISSUE TITLE
Current nightly PG broken ( on macOS at least )

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#554]
See: https://github.com/openframeworks/openFrameworks/issues/8053 

Something between now and April breaks the creation of folders that the PG used to do, which makes project generation fail. 

Could it be related to this PR and the new entitlements for the command line PG?
https://github.com/openframeworks/projectGenerator/commit/853b10497c92410b43859cddb19e88d315b8fd31

**Comment by dimitre** [comment]
I think this now can be closed
