### ISSUE TITLE
PG not detecting OF path correctly ( regression ) 

### ISSUE THREAD

**Issue by ofTheo** [openframeworks/projectGenerator#555]
Currently when you open the PG when packaged in the OF nightly download it uses the OF/projectGenerator/ path as the OF path instead OF/

This is a regression as it used to automatically detect: 
`/Users/theo/Downloads/of_v20240717_osx_release/` 

But currently it detects: 
`/Users/theo/Downloads/of_v20240717_osx_release/projectGenerator`

See: 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/910213c2-6c47-400d-a62c-a9b466ebf9cb">

Not a major problem, but definitely a regression and adds an extra step.

**Comment by danoli3** [comment]
Yeah basically the Electrion side is trying to figure out stuff
I added some command line systems up for:
GUI App -> C++ ProjectGenerator with correct openFrameworks dir on first start (if not set) 
That should fix this

**Comment by ofTheo** [comment]
these seems fixed now but there are other issues breaking project creation with addons
