### ISSUE TITLE
Latest v.65 doesn't add local frameworks. ofxMidi doesn't add CoreMidi

### ISSUE THREAD

**Issue by dimitre** [openframeworks/projectGenerator#557]
Latest v.65 doesn't add local frameworks. ofxMidi doesn't add CoreMidi
cc: @danoli3

**Comment by dimitre** [comment]
it seems PG is prepending an absolute path to the addon name
```
/Volumes/tool/ofw/addons/ofxMidi/CoreMIDI
```

**Comment by dimitre** [comment]
I've made this ugly patch locally just to use PG today 
```c++
	else if(variable == ADDON_FRAMEWORKS){
		size_t found=value.find('/');
		if (found==string::npos) { // This path doesn't have slashes
			addReplaceStringVector(frameworks, value, emptyString, addToValue);

		} else {
			addReplaceStringVectorPre(frameworks, value, addonRelPath, addToValue);
		}
	}
```

**Comment by ofTheo** [comment]
Nice! 
Not too ugly and definitely needed. 👍

**Comment by dimitre** [comment]
ok applied here: https://github.com/openframeworks/projectGenerator/pull/558
it can be done better later.

**Comment by dimitre** [comment]
closed by https://github.com/openframeworks/projectGenerator/pull/558
