### ISSUE TITLE
Missing sketchAdjectives.txt

### ISSUE THREAD

**Issue by JennShen** [openframeworks/projectGenerator#56]
When I click on the button next to where you type the project name, the following error pops up. It seems as though the document sketchAdjectives.txt is missing.

<img width="455" alt="error_image" src="https://cloud.githubusercontent.com/assets/14191967/10530551/7a2533be-736e-11e5-837a-617d85f545b7.png">

**Comment by ofZach** [comment]
thanks for the error report!  I think this should be fixed now: 

https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorElectron/index.js#L243
https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorElectron/index.js#L437

but I will take a look at the next nightly to see if it is.  At least locally I'm not seeing this error anymore.

**Comment by ofZach** [comment]
this is fixed in the nightly !  thanks for the error report, I'm going to close this for now...
