### ISSUE TITLE
AssetsLibrary added to iOS projects that require it

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#58]
https://github.com/openframeworks/openFrameworks/issues/4290

Just for projects that require ```ofxOpenCv``` in their addons.make

So currently:
- opencvFaceExample
- opencvExample

**Comment by ofZach** [comment]
I really think the easiest way to do this is via addon_config.mk -- see here for example: 

https://github.com/danomatika/ofxMidi/blob/master/addon_config.mk#L157

how ofxMidi adds the CoreMIDI framework on ios.

**Comment by danoli3** [comment]
That seems to easy! I'll do it now

**Comment by ofZach** [comment]
I think this is fixed now via this: 

https://github.com/openframeworks/projectGenerator/commit/3852fb414cca49198b326e21deab4992ac571657

Am I right to assume that this path: 

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/

is the canonical path for system frameworks on ios ?

also, is this framework called "AssetsLibrary" ?  (I couldn't find AssetsFramework...)

now if the addon_config.mk looks like this: 

<img width="769" alt="screen shot 2015-10-18 at 5 59 58 pm" src="https://cloud.githubusercontent.com/assets/142897/10566917/4028ebfa-75c2-11e5-8e81-6c3880b59506.png">

you should see this in the output: 

<img width="291" alt="screen shot 2015-10-18 at 5 59 27 pm" src="https://cloud.githubusercontent.com/assets/142897/10566918/46fb693a-75c2-11e5-9d50-1df53191d7d7.png">

let me know if this helps....

**Comment by ofZach** [comment]
ps: if you rebuild the command line tool to test this, this is the command I used: 

```./projectGenerator -p"ios" -o"../../../../" ../../../../examples/ios/opencvExample/
open ../../../../examples/ios/opencvExample/opencvExample.xcodeproj```

**Comment by danoli3** [comment]
You are correct! It's AssetsLibrary D:

**Comment by danoli3** [comment]
Okay now the issue really is with the project generator.

It adds the Framework to Xcode, however does not add the target to the project. 
So it still errors:

<img width="299" alt="screen shot 2015-10-19 at 9 35 28 am" src="https://cloud.githubusercontent.com/assets/830748/10567082/f5b65dd6-7644-11e5-85d2-54b4ee6c0f7e.png">

**Comment by ofZach** [comment]
thanks,  investigating...

**Comment by ofZach** [comment]
ok I think I fixed this but I'm not 100% about regular osx w/ frameworks so I'm going to test this PR a little bit more.

**Comment by ofZach** [comment]
I think this is good, closing..

**Comment by danoli3** [comment]
Nice I'll try it out as well
