### ISSUE TITLE
Code style of ofApp template

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#59]
The current styling of the code doesn't work well with the Xcode default styling.

![screen shot 2015-10-17 at 15 41 52](https://cloud.githubusercontent.com/assets/3796674/10558990/a5549e80-74e5-11e5-8cd7-3370c77a7492.png)

Also, these two lines should be swapped to have the same order as in the implementation file.

```c++
void dragEvent(ofDragInfo dragInfo);
void gotMessage(ofMessage msg);
```

**Comment by ofZach** [comment]
The templates live in openframeworks so can you put an issue there?  It's not clear what you mean by default Xcode styling.  Also OF is cross platform and we have a style guide for the code to make it work the best among all platforms, maybe you can take a look at it and make suggestions with regards to that ?

**Comment by thomasgeissl** [comment]
Sorry for not being clear, I was referring to indentations. But I just saw that it is correct according to the style guidelines. Thanks for the guidelines hint.
I will fix the ordering in the oF repo.

**Comment by arturoc** [comment]
yeah i don't like that indentation of the public, protected... either and the default in xcode is the default in other IDEs too so you always have to fix it when adding other accessors, anyway let's discuss it in the OF repo
