### ISSUE TITLE
Rescan link does not work

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#60]
I just opened an old project where one of its depending addons is missing. In my case the projectGenerator complains that ofxCv is missing, I should download, put the addon in the addons folder and finally rescan it. The provided rescan link does not work, so I had to reopen the projectGenerator.

![screen shot 2015-10-17 at 16 40 06](https://cloud.githubusercontent.com/assets/3796674/10559330/9f5076c2-74ee-11e5-956a-c56bcca6060d.png)

**Comment by bakercp** [comment]
Confirmed that this does not work on visual studio release either.

**Comment by ofZach** [comment]
thanks for the helpful report. 

this is fixed via https://github.com/openframeworks/projectGenerator/commit/2903e5f2674c44ebe7d1b368854f35aa1f76d74f
