### ISSUE TITLE
local addons

### ISSUE THREAD

**Issue by ofZach** [openframeworks/projectGenerator#61]
here's my thought about how to do local addons: 

(a) allow user to specify them in the settings.json

<img width="863" alt="screen shot 2015-10-17 at 11 32 29 am" src="https://cloud.githubusercontent.com/assets/142897/10559610/f5fb2c64-74c2-11e5-972f-6dd855699c2a.png">

(b) convert them internally in the GUI to an absolute path (it just gets confusing to have relative paths from OF and relative paths from the project.   This absolute path is based on the path to OF so if OF moves, this doesn't break. 

(c) show them in the drop down as well as the core addons

<img width="519" alt="screen shot 2015-10-17 at 11 30 56 am" src="https://cloud.githubusercontent.com/assets/142897/10559626/4d1b82e6-74c3-11e5-922e-757fe4364a28.png">

(d) pass them into the PG via their absolute path. 

```projectGenerator  -o"/Users/zachlieberman/Documents/openframeworks/git/openFrameworks" -a"/Users/zachlieberman/Documents/openframeworks/git/openFrameworks/otherAddons/ofxDummy" -p"osx" "/Users/zachlieberman/Documents/openframeworks/git/openFrameworks/apps/myApps/myImposingSketch"```

(e) they get converted to relative paths in the PG and added to the project

<img width="523" alt="screen shot 2015-10-17 at 11 31 14 am" src="https://cloud.githubusercontent.com/assets/142897/10559623/3a3e39a2-74c3-11e5-880e-c7f679fbc787.png">

all this is generally working, but I haven't figured out what do about importing?  (ie, read the addons.make, convert these to absolute paths, attempt to match them against the set local addons, etc).  The gui "update" command kind of trashes the addons.make file so it's important to figure out what import should do. 

cc @mattfelsen @arturoc

**Comment by arturoc** [comment]
mmh, adding them in the json is kind of weird. the idea is that each project would have it's own addons so you can do modifications to them... but if they have to be specified in the json file for the PG then you have to change them for every project or use always the same which defeats the purpose of having local addons.

i would add a path selector that allows you to look for a directory in the fs and adds it to a list control, perhaps even a text control where it adds evey local addon line by line so you can just edit the paths later manually or copy paste from somewhere?

**Comment by arturoc** [comment]
otherwise we can leave this out by now, people can still add them in the addons.make and update the project or just directly use the command line tool

**Comment by mattfelsen** [comment]
Hey Zach. Most of this sounds good to me. Why specify the addons individually in settings.json instead of setting a folder for local addons though? When I use OFPlugin, that's my general pattern...if I'm switching between projects (i.e. entirely different projects, not just different apps within the same project) that have their own folders, it's not too big a deal to set the path for your addons folder

**Comment by ofZach** [comment]
@arturoc -- yeah this is all kind of complicated :) they don't need to be in the gui, but right now, the gui kind of rewrites addons.make when you do an import, and we need to figure out a way to respect local addons.    Also, I figured that folks might want to use a gui to pick addons that are not in the addons folder. 

@mattfelsen sure we could do a folder (or folders) instead of individual addons. 

I'm ok to leave this for now and just a find a way to be respectful of local addons in the addons.make file (which won't work now).  Since we do "import" we try to choose the addons that are in the addons.make and let you interact with them like remove them, etc.   I kind of don't know what to do if they are not in the dropdown...   ¯\_(ツ)_/¯

one larger question is if it would be a good idea to package the command line tool outside of the gui, right now it's kind of embedded in the gui.  Making it more visible and giving people instructions about how to use it could be good....

**Comment by ofZach** [comment]
```i would add a path selector that allows you to look for a directory in the fs and adds it to a list control, perhaps even a text control where it adds evey local addon line by line so you can just edit the paths later manually or copy paste from somewhere?```

this is probably a good solution...  will investigate.

**Comment by mattfelsen** [comment]
Maybe as a stop-gap measure for now, when importing addons.make and finding local addons, the gui could just keep track of them and pass it along to the command line. You wouldn't be able to remove an addon from the project, but at least you wouldn't lose them either?

**Comment by ofZach** [comment]
yes this seems like the simplest and least destructive thing :)   I think showing that we are doing this is helpful (will think about how to do this...)

**Comment by mattfelsen** [comment]
Yea, maybe a well with something like "These additional local addons will be added to the project... Use the command line tool directly to update this project without these addons" and/or point to running `projectGenerator --help`

**Comment by ofZach** [comment]
how about something like this? 

<img width="445" alt="screen shot 2015-10-18 at 4 21 03 pm" src="https://github-cloud.s3.amazonaws.com/assets/142897/10566402/46b70578-75b4-11e5-996f-129951c7969a.png">

I've got it working on import, will just reflect this list back on update...

**Comment by mattfelsen** [comment]
:+1: Dig it.

**Comment by ofZach** [comment]
ok I think I've done this ok w/ the last commit: 

https://github.com/openframeworks/projectGenerator/commit/711139098d8cb5e7199c308b8df7b338ceb4b9c9

but def invite testing...

local addons get added right it seems to me, they come in exactly as written the addons.make file: 

projectGenerator  -o"/Users/zachlieberman/Documents/openframeworks/git/openFrameworks" -a"ofxCv,../../../otherAddons/ofxDummy" -p"osx" "......"

the local addon has to resolve to a real path, meaning either:  

```path.join( project path, project name, local addon path)```

or

```local addon path```

need to be real paths via fs.exists(...).   If you are using relative paths for local addons and they work, it should be fine.  It also means you can use absolute paths (but the PG I think will convert these into relative paths at some point). 

probably the overall addon order in the addons.make will get altered, but that shouldn't matter.  At the moment, all local addons kind of get pushed to the end of the -a"....." flag.

**Comment by ofZach** [comment]
gonna close this but invite testing and feel free to reopen.

**Comment by arturoc** [comment]
looks good to me

**Comment by mattfelsen** [comment]
Looks good for me on Windows too, after adding the fix I submitted in #66
