### ISSUE TITLE
Remove ofxiOS / ofxMultiTouch / ofxAccelerometer from iOS Project Generator selection

### ISSUE THREAD

**Issue by danoli3** [openframeworks/projectGenerator#62]
A common error for iOS Projects when using the project generator is to select the ofxiOS addon and related addons, such as ofxAccelerometer and ofxMultiTouch.

These addons are already included by default and it causes strange semantic errors by having multi of the same in each project.

Hiding these from being selected / seen will be a easy fix

**Comment by ofZach** [comment]
True -- will take a look.  I believe we've hidden these in the past.

**Comment by ofZach** [comment]
are there any platforms where hiding these would be problematic?  (ie, could we hide these addons in all cases?)

**Comment by danoli3** [comment]
I don't think so. @arturoc

**Comment by arturoc** [comment]
yes we can hide this, also ofxAndroid. 

ofxMultitouch is gone now

**Comment by arturoc** [comment]
and ofxEmscripten should be hidden too

**Comment by ofZach** [comment]
just a reminder to do this for 0.9...  I think it's an easy mistake to make on IOS and it's fairly trivial to fix this.

**Comment by ofZach** [comment]
does this list look right?

https://github.com/openframeworks/projectGenerator/pull/72/files#diff-cc004138e83db4191a410f65833cbe83R83

if so, I'm happy to merge this. 

is there an instance (osx, etc) where you would want ofxAccelerometer visible?   that was one that it felt a little weird to hide. 

moving these out of the addons folder at some point will be good to consider, to me these seem more like core "components" than addons....

**Comment by ofZach** [comment]
merged this,  closing this issue...

**Comment by danoli3** [comment]
Looks right!
