### ISSUE TITLE
Library not loaded: @executable_path/libfmodex.dylib

### ISSUE THREAD

**Issue by Qix-** [openframeworks/projectGenerator#68]
Upon a fresh clone of OF and projectGenerator, I built the command line project generator and then tried to generate a project with it.

```
dyld: Library not loaded: @executable_path/libfmodex.dylib
  Referenced from: /src/openframeworks.openframeworks/apps/projectGenerator/commandLine/bin/./projectGenerator
  Reason: image not found
[1]    9384 trace trap  ./projectGenerator
```

What am I missing here? I see lots of Xcode solutions but none that really describe what needs to be done here.

**Comment by ofZach** [comment]
I'm not sure why but this commit didn't seem to stick: 

https://github.com/openframeworks/projectGenerator/commit/5831a984fcede165ce04a27d2ba6951ec9b825d7?diff=unified

the Project.xcconfig for that project needs to be the same as: 

https://github.com/openframeworks/openFrameworks/blob/master/scripts/templates/nofmod/Project.xcconfig

or else fmod gets linked to the command line tool.  I'll take a closer look at the repo but in the meantime, replacing this file should fix it.

**Comment by arturoc** [comment]
are you compiling using xcode or the makefiles? the makefiles won't take the xcconfig file into account so that might be the problem

**Comment by Qix-** [comment]
@arturoc makefiles.

**Comment by arturoc** [comment]
that's the problem then, this particular project won't work when compiled with the makefiles because it needs an special config where it won't link against that library, you'll need to compile it with xcode, another solution is to put libfmodex.dylib next to the executable

**Comment by ofZach** [comment]
the xcconfig changes the linking to avoid linking against fmod (when you compile on xcode), I think you'll need to basically do the same thing if you want to use a makefile.

**Comment by arturoc** [comment]
in the linux makefiles there's an option to do this, it could be easily included in the osx ones:
```
ifeq ($(USE_FMOD),0)
	PLATFORM_CORE_EXCLUSIONS += $(OF_LIBS_PATH)/fmodex/%
	PLATFORM_CORE_EXCLUSIONS += $(OF_LIBS_PATH)/openFrameworks/sound/ofFmodSoundPlayer.cpp
endif
```

then you can run

```
make USE_FMOD=0
```

if you want to send a PR?

**Comment by Qix-** [comment]
Perhaps I should clarify; I build the commandLine project generator using `xcodebuild`. It works. Trying to *generate* a project gets me the error message in the original post.

**Comment by arturoc** [comment]
mmh, that's strange the xcconfig file seems correct. does the gui version in the nightly builds work for you? that should use the same project file that is in the repo.

**Comment by ofZach** [comment]
sorry I'm not super familiar with xcodebuild.  I just rebuilt the app using xcodebuild and I'm not seeing the dylib problem -- I'm able to generate projects just fine with the "projectGenerator" executable this buillds..  Can you maybe clean everything, run xcodebuild and paste the output into a pastebin?

**Comment by Qix-** [comment]
Did a full `git clean -dfx` and then

```
$ pwd
/src/openframeworks.openframeworks/apps/projectGenerator/commandLine
$ xcodebuild
. . .
** BUILD SUCCEEDED **
$ echo $?
0
$ pwd
/src/openframeworks.openframeworks/examples/gl/multiLightExample
$ ../../../apps/projectGenerator/commandLine/bin/projectGenerator .
dyld: Library not loaded: @executable_path/libfmodex.dylib
  Referenced from: /src/openframeworks.openframeworks/examples/gl/multiLightExample/../../../apps/projectGenerator/commandLine/bin/projectGenerator
    Reason: image not found
    Trace/BPT trap: 5
```

**Comment by ofZach** [comment]
can you put the contents of . . .  into pastebin?  ie, what you see between these two lines

    $ xcodebuild
    . . .
    ** BUILD SUCCEEDED **

thanks

**Comment by Qix-** [comment]
http://pastebin.com/6YgnmTJm

**Comment by ofZach** [comment]
thanks! I am unable to reproduce.  

Can you check your xcconfig file 

https://github.com/openframeworks/projectGenerator/blob/master/commandLine/Project.xcconfig

it should say "OF_CORE_FRAMEWORKS_REDUCED" as per: 

https://github.com/openframeworks/projectGenerator/blob/master/commandLine/Project.xcconfig#L21

I just cleaned and rebuilt with xcodebuild and I see string in my output, but I don't see that string in yours, which makes me think you don't have the latest version of master or there's something wrong with that file. 

This xconfig drops fmod, which means it doesn't get linked in to the executable, which is what is happening to your project at the moment.

**Comment by Qix-** [comment]
Well, it was all updated a few days ago, but sure enough I just pulled again and everything builds and runs fine. Maybe I got a weird in-between commit or something; who knows.

Thanks!

**Comment by ofZach** [comment]
cool glad it's working (and sorry the submodule isn't pointing right, I always forget to update the main repo to point at the right submodule commit...)

**Comment by Qix-** [comment]
No problem! :dancer:
