### ISSUE TITLE
can't build projectGenerator/commandLine

### ISSUE THREAD

**Issue by avilleret** [openframeworks/projectGenerator#7]
still running after a working project for building shader tutorials (see https://github.com/openframeworks/openFrameworks/issues/4194), I tried to build what looks like a command line tool project generator to my eyes, but it fails with : 

~~~~
/home/antoine/lib-src/openFrameworks/apps/projectGenerator/commandLine/src/main.cpp:14:28: fatal error: CBLinuxProject.h: Aucun fichier ou dossier de ce type
 #include "CBLinuxProject.h"
~~~~

I'm running Ubuntu 64bit and try to build this one from OpenFrameworks submodule

any hint ?

**Comment by ofZach** [comment]
I think you are using windows codeblocks files on linux, I also don't know how up to date those files are!

Can you try adding these files -- 

https://www.dropbox.com/s/p03gzljhzmiiwcw/linuxTest.zip?dl=0

to the project and see if it works?  I've just "generated" linux project files for this project but can't test over here.  If it works, I'll commit this...  (I need to rename them to commandLine_linux64.cbp, etc)

**Comment by avilleret** [comment]
hum... strangly `make` build fine now whilst you don't seems to made any changes in the `Makefile`.
Since this afternoon, I updated the main ofx repo.
The Code::Block project doesn't work.
The build fails with : 

~~~~
/usr/include/c++/4.9/bits/c++0x_warning.h|32|error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.|
../../../libs/openFrameworks/utils/ofUtils.h|4|fatal error: utf8.h: Aucun fichier ou dossier de ce type|
~~~~

**Comment by ofZach** [comment]
are you compiling against git master branch or 0.8.4?

**Comment by avilleret** [comment]
I have openFrameworks/master ccd3b06 and projectGenerator/master 9749d67

**Comment by ofZach** [comment]
ping @arturoc / @openframeworks/linux these files were built with the PG, so maybe something is wrong with the linux cb template or do I have something out of date?

**Comment by ofZach** [comment]
also one thing this flags is that project generator current has naming conflicts with linux cb and windows cb, but I guess since we are dropping windows cb, this should be ok?.  I am still of the opinion that we should use seperate folders for each platform and I'm happy to submit a PR with this change (it would make the folder so much cleaner)

**Comment by moxor** [comment]
i am getting this error because when i pull the master the ofxprojectGenerator isn't in the addons folder

**Comment by moxor** [comment]
okey its different. The version i get with submodules is throwing this error.
