### ISSUE TITLE
linux64, PG frontend does not find command line app

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#76]
I just downloaded the nightly build of_v20151030_linux64_release and it seems that  the command line app binary is missing. Probably just a linux bug.
![screenshot from 2015-10-30 16 33 37](https://cloud.githubusercontent.com/assets/3796674/10850073/0383e28e-7f24-11e5-9550-64430a85d4e5.png)

**Comment by ofZach** [comment]
I think you have to build and install the command line app -- @arturoc there's a script for that, right?

**Comment by ofZach** [comment]
I think this is the script: 

https://github.com/openframeworks/openFrameworks/blob/master/scripts/linux/compilePG.sh

in the download you'll find it in scripts.  it should build and install the command line tool so that the electron app works....

**Comment by thomasgeissl** [comment]
Is not it packaged int the nightly builds?

**Comment by ofZach** [comment]
I think you have to build the command line tool on linux b/c it's hard or impossible to release a version that would work across different distros.

**Comment by thomasgeissl** [comment]
ah, okay. Thanks.
If I remember correctly, the command line app binary was included in the osx version. Not sure if this is still the case.

**Comment by ofZach** [comment]
it is !  it's just on linux that I think we have this issue...  It definitely should be added to the install guides / info.

**Comment by arturoc** [comment]
yes in linux OF binaries are not compatible between versions so there's no way to pack an app that would work across versions. you need to run the compilePG.sh script in scripts/linux

**Comment by thomasgeissl** [comment]
ok, thanks. I this documented somewhere?

I cannot compile it right now. 
```sh
/home/thomasgeissl/programming/of/of_v20151030_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofMainLoop.o): In function `ofMainLoop::run(std::shared_ptr<ofAppBaseWindow>, std::shared_ptr<ofBaseApp>)':
ofMainLoop.cpp:(.text+0xad7): undefined reference to `ofCoreEvents::notifySetup()'
/home/thomasgeissl/programming/of/of_v20151030_linux64_release/libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofAppGLFWWindow.o): In function `ofAppGLFWWindow::close()':
ofAppGLFWWindow.cpp:(.text+0x818): undefined reference to `ofCoreEvents::disable()'

```
The same happens with other examples too.

**Comment by arturoc** [comment]
what linux are you using? that's working for me fine in the nightlies

if you are using ubuntu 15.10 you need to run the install_dependencies script even if you've installed it recently since it needs to recompile poco to be compatible with gcc 5

**Comment by thomasgeissl** [comment]
I do not know what I did wrong. I was looking into ofEvents.cpp, did not find any missing implementations and probably saved it. Then it took me quite long to compile it, so I guess it compiled the core again. And it compiled fine.
I tried to reproduce it, but I was not able to.
I am using ubuntu 15.04.

**Comment by ofZach** [comment]
closing this issue then -- thanks for reporting it.
