### ISSUE TITLE
Handle Windows paths containing spaces

### ISSUE THREAD

**Issue by paulmasri** [openframeworks/projectGenerator#77]
[Based on nightly build of_v20151106_vs_nightly.zip]

If there is a space in the path where the projectGenerator is stored *(or the project path, or both?)*, such as in the User's folder, then a compile error occurs.

e.g. For user `Forename Surname` where OF is installed within the user's workspace you get

```
Command failed: C:\WINDOWS\system32\cmd.exe /s /c "C:\Users\Forename\ Surname\Documents\of_v20151106_vs_release\projectGenerator-vs\resources\app\app\projectGenerator  -o"C:\Users\Forename Surname\Documents\of_v20151106_vs_release" -a" " -p"vs,vs" "C:\Users\Forename Surname\Documents\Developer\of_v20151106_vs_release\apps\myApps\mySketch""
'C:\Users\Forename\' is not recognized as an internal or external command,
operable program or batch file.
```

(This is my first interaction on the OF github repos. Apologies if this is the wrong way to go about things.)

**Comment by ofZach** [comment]
thanks for the report, this is helpful.  I will take a look at this, we added quotes for everything else, but I think we either need quotes here or to disambiguate spaces with a symbol (I think it's something like C:\Users\Forename/ Surname\Documents\of_v20151106_vs_release)....

**Comment by ofZach** [comment]
just a quick note that on OSX this seems fine -- these lines seems to be doing the right thing but be posix specific: 

https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorElectron/index.js#L567
https://github.com/openframeworks/projectGenerator/blob/master/projectGeneratorElectron/index.js#L649

looking for the right windows solution -- might be something like a caret symbol  : 

http://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks

solution is in the works, hold tight...

**Comment by ofZach** [comment]
I think this should work as a fix -- changing the two lines that look like this: 

    pgApp = pgApp.replace(/ /g, '\\ ');

to this: 

    if( arg.platform == 'osx' || arg.platform == 'linux' || arg.platform == 'linux64' ){
        pgApp = pgApp.replace(/ /g, '\\ ');
    } else {
        pgApp = pgApp.replace(/ /g, '^ ');
    }

if you can, can you find the index.js inside your nightly package and try swapping those lines and check if this helps?  

will check on windows when I have a moment (also cc @mattfelsen who's been helping here with windows testing...)

**Comment by ofZach** [comment]
sorry that doesn't seem to work, but this does:

     if( arg.platform == 'osx' || arg.platform == 'linux' || arg.platform == 'linux64' ){
         pgApp = pgApp.replace(/ /g, '\\ ');
     } else {
          pgApp = pgApp = "\"" + pgApp + "\"";
     }

**Comment by ofZach** [comment]
(still working on open in ide, which seems to fail with path with spaces on it or using quotes....)

**Comment by ofZach** [comment]
(note, this seems help with 'start' -- http://superuser.com/questions/239565/can-i-use-the-start-command-with-spaces-in-the-path)

**Comment by ofZach** [comment]
fixed via https://github.com/openframeworks/projectGenerator/pull/78
