### ISSUE TITLE
PG Electron - Need to escape "pgApp" path better for shell

### ISSUE THREAD

**Issue by robotconscience** [openframeworks/projectGenerator#89]
_Issue_
Path to project generator app is not fully escaped for shell.

_Description_
Line 570 in index.js escapes any spaces in path, but does not account for other characters that are problematic. For example, my OF lives in my Dropbox and I have personal and company account. Dropbox by default keeps these in separate folders: "Dropbox (Personal)" and "Dropbox (Company Name)". When I tried to create a project, it fails with this message:
```
Command failed: /bin/sh -c /Users/brettrenfer/Dropbox\ (Personal)/Code/OF/of_v0.X.X_github/apps/projectGenerator/projectGeneratorElectron/app/projectGenerator -v -o"/Users/brettrenfer/Dropbox (Personal)/Code/OF/of_v0.X.X_github" -a" " -p"osx" "/Users/brettrenfer/Dropbox (Personal)/Code/OF/of_v0.X.X_github/apps/myApps/myTolerantSketch"
/bin/sh: -c: line 0: syntax error near unexpected token `Personal'
```

If I add code to escape parentheses, it works:
```
    pgApp = pgApp.replace(/ /g, '\\ '); //existing line
    pgApp = pgApp.replace("(", '\\(');
    pgApp = pgApp.replace(")", '\\)');
```

_Potential fixes_
* Something like this Node library could be great: https://github.com/xxorax/node-shell-escape
* I attempted to add that, but unfortunately making Node apps like this isn't really my bag... Hoping someone smarter than me can figure out how to add that library, OR knows all of the characters we may need to escape :)

**Comment by ofZach** [comment]
ah thanks - I will take a look at that....  thanks for the thorough report and potential solutions.

**Comment by ofZach** [comment]
hmmm,  I'm not seeing a problem when I use () in the path....  

```
[notice ] -----------------------------------------------
[notice ] setting OF path to: /Users/zachlieberman/Desktop/of (yo)
[notice ] from -o option
[notice ] target platform is: osx
[notice ] project path is: /Users/zachlieberman/Desktop/of (yo)/apps/myApps/mySketch234
[notice ] setting up new project /Users/zachlieberman/Desktop/of (yo)/apps/myApps/mySketch234
[notice ] saving addons.make
[notice ] project created! 
[notice ] -----------------------------------------------


1 project created [notice ] in 0 seconds
```

how can I recreate this ?

**Comment by robotconscience** [comment]
Ah geez -- I didn't pull the submodule master before reporting the bug! Sorry, Zach. Looks like you guys just need to update the module in the master OF repo !

**Comment by ofZach** [comment]
oh ok !  yeah I forget to do this -- good to test the download (0.9.0) now as well, unless it's explained, I sort of think the error is release specific.  closing this now, feel free to reopen if you hit other glitches.

**Comment by arturoc** [comment]
the script that creates the package always pulls master to avoid this problem so it should be ok
