### ISSUE TITLE
Feature request: cross plattform project config file

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/projectGenerator#9]
I would like to be able to save a project config file, so i can modify it later and add new addons or libraries. 
Also if I want to put a project on github, it would be enough to just include a cross plattform config and other users can generate their own IDE specific projects.
This could be a simple json file.

Are there any disadvantages of this approach? 
I could give it a try in october.

Just for reference here is a forum post. 
http://forum.openframeworks.cc/t/updating-projects-using-the-project-generator/19946

**Comment by bilderbuchi** [comment]
One disadvantage I know is that make has a very bad time parsing json for consumption, which is why we haven't done this in the past, relying instead on config.make files. @arturoc knows more I think

**Comment by thomasgeissl** [comment]
I not sure if we are talking about the same thing.
I would like the project generator to be able to save, load and modify an xml/json based project config file and generate an xcode project, makefiles or a codeblocks project, based on this project config.

**Comment by Daandelange** [comment]
I think you are talking about the same thing but different. :angel: 
The JSON/XML file you mention already exists as a `config.make` and `addons.make` file. (but there still has some work to be done)
With the current [PG Legacy](https://github.com/openframeworks/projectGenerator/tree/master/projectGeneratorLegacy), you can `update` a project; it then checks `addons.make` for addons to include, even if you didn't select them in the UI. (at least, on Mac)

**Comment by thomasgeissl** [comment]
Oh sorry, I did not know that, I thought the pg overrides addons.make and does not add prevously selected addons. Probably because there is no feedback shown on the GUI and I am not used to the current workflow. 
It would be more intuitive if one can decide between new project and open project at the very first step and then edit the settings and finally generate project files.
But I see your point that this common config is already there and does not have to be a json or xml file.
Does the pg create addons.make and config.make on every platform?

I still would love to be able to manage addons and paths better, like removing addons from existings projects or adding addons which are not in the default path. I could try to do some work on this, once I have time (probably in october).

**Comment by Daandelange** [comment]
Yes, I think that way is more intuitive too and we're having some similar discussions about it here:
https://github.com/openframeworks/projectGenerator/issues/5
Anyways, a brand new PG is being baked, feel free to contribute to it once you have time :)

**Comment by thomasgeissl** [comment]
This looks promising. I will check it out once it is released.

I still prefer having only one config file instead of addons.make and config.make. We would be able to store more detailed information, like addon paths and there would be only one file laying around, probably less confusing for beginners. 
But that is just my personal preference.

Here is a little sketch how such a config file could look like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<PROJECT>
	<METADATA>
		<META id="appName" value="myApp" />
		<META id="version" value="v1.0.0" />
		<META id="organization" value="myOrganization" />
		<!-- ... -->
	</METADATA>
	<ADDONS>
	    <ADDON id="ofxGui" path="../../../addons/ofxGui"/>
	    <ADDON id="ofxOpenCv" /> <!--path="../../../addons/ofxOpenCv"/>-->
	    <ADDON id="ofxCustomPathAddon" path="~/projects/myProject/addons/ofxCustomPathAddon"/>
	</ADDONS>
	<SOURCES>
		<SOURCE path="src/*" /> <!-- could be also the default, no need to add -->
		<SOURCE path="~/projects/common/helper.h" />
	</SOURCES>
	<!-- linking, compilation flags -->
	<!-- ... plattform="osx" -->
</PROJECT>
```

Projects could be easliy created by passing this file to the project generator or modified/configured by opening it with the projectGenerator.

I think this can be closed, as #5 already covers my main point of being able to modify a project.

**Comment by Daandelange** [comment]
I agree on having only 1 config file but not on including addon-specific information in it. Each addon has it's own configuration file which handles (on it's own) which files to import for a project. I guess they made that choice for a good reason but can't confirm anything. Probably to prevent having duplicated information and so updating addons is easier. (regarding versioning and bug fixing, etc). Imagine an addon updates but not your project's config file: it would be even more a pain in the ass. :angel: 

So the role of the Project generator is to generate (amongst others) a project file from a given addons list.

I also think we can close this :+1:

**Comment by thomasgeissl** [comment]
Got that and it absolutley makes sense.
There is no addon-specific information in it, just an optional custom path to the addon, so an addon can be at a different location.
