### ISSUE TITLE
OTHER_CFLAGS not set when generating Xcode projects

### ISSUE THREAD

**Issue by danomatika** [openframeworks/projectGenerator#96]
OTHER_CFLAGS are not being set when generating Xcode projects. This means ofxPd Xcode projects will not build in 0.9.0 ;(

I had this fixed with https://github.com/ofZach/projectGeneratorSimple/pull/62, but it seems not everything made it into this repo. I believe the fix is to change `OTHER_CPLUSPLUSFLAGS` to `OTHER_CFLAGS` as in my original PR on xcodeProject.cpp line 1053: https://github.com/openframeworks/projectGenerator/blob/master/ofxProjectGenerator/src/projects/xcodeProject.cpp#L1053

**Comment by danomatika** [comment]
I can confirm that's the fix. Just build the commandLine app with the small change and generated a successful ofxPd pdExampleIOS project.

**Comment by arturoc** [comment]
this probably got lost in some of the merges we did to have a common code base, can you send a PR?

thanks!
